class_name TaskDescriptions
extends Node

const TaskName:= {
Tasks.tasks.Debut : "Debut",
Tasks.tasks.Search : "Search Mission",
Tasks.tasks.Checking : "Background Check",
Tasks.tasks.Shootout : "Shootout Picnic",
Tasks.tasks.PastDelivery : "Delivery from the Past",
Tasks.tasks.BPDepot : "BP Depot",
Tasks.tasks.Bunker1 : "The Bunker",
Tasks.tasks.Bunker2 : "The Bunker",
Tasks.tasks.BadRep : "Bad Rep Evidence",
Tasks.tasks.IceCream : "Ice Cream Cones",
Tasks.tasks.Renegades : "No Place for Renegades",
Tasks.tasks.Documents : "Documents",
Tasks.tasks.Postman1 : "Postman Pat",
Tasks.tasks.ShakingupTeller : "Shaking up the Teller",
Tasks.tasks.Punisher1 : "The Punisher",
Tasks.tasks.Punisher2 : "The Punisher",
Tasks.tasks.Punisher3 : "The Punisher",
Tasks.tasks.Punisher4 : "The Punisher",
Tasks.tasks.Punisher5 : "The Punisher",
Tasks.tasks.Punisher6 : "The Punisher",
Tasks.tasks.Anesthesia : "Anesthesia",
Tasks.tasks.Grenadier : "Grenadier",
Tasks.tasks.TestDrive1 : "Test Drive",
Tasks.tasks.Mediator : "Perfect Mediator",
Tasks.tasks.PolikhimHobo : "Polikhim Hobo",
Tasks.tasks.Regulated : "Regulated Materials",
Tasks.tasks.BigCustomer : "Big Customer",
Tasks.tasks.Intimidator : "Intimidator",
Tasks.tasks.EasyJob1 : "Easy Job",
Tasks.tasks.EasyJob2 : "Easy Job",
Tasks.tasks.Recon : "Reconnaissance",
Tasks.tasks.Shortage : "Shortage",
Tasks.tasks.Aq1 : "Operation Aquarius",
Tasks.tasks.Aq2 : "Operation Aquarius",
Tasks.tasks.Gasan1 : "Sanitary Standards",
Tasks.tasks.Gasan2 : "Sanitary Standards",
Tasks.tasks.Painkill : "Painkiller",
Tasks.tasks.Pharm : "Pharmacist",
Tasks.tasks.DHistory : "Disease History",
Tasks.tasks.Car : "Car Repair",
Tasks.tasks.Supply : "Supply Plans",
Tasks.tasks.HCP1 : "Health Care Privacy",
Tasks.tasks.HCP2 : "Health Care Privacy",
Tasks.tasks.HCP3 : "Health Care Privacy",
Tasks.tasks.HCP4 : "Health Care Privacy",
Tasks.tasks.Athlete : "Athlete",
Tasks.tasks.PClinic : "Private Clinic",
Tasks.tasks.HCP5 : "Health Care Privacy",
Tasks.tasks.Decontam : "Decontamination Service",
Tasks.tasks.Wares : "General Wares",
Tasks.tasks.Coll1 : "Colleagues",
Tasks.tasks.Coll2 : "Colleagues",
Tasks.tasks.Coll3 : "Colleagues",
Tasks.tasks.Postman2 : "Postman Pat",
Tasks.tasks.Curiosity : "Out of Curiosity",
Tasks.tasks.Crisis : "Crisis",
Tasks.tasks.Seaside : "Seaside Vacation",
Tasks.tasks.LostContact : "Lost Contact",
Tasks.tasks.Trafficking : "Drug Trafficking",
Tasks.tasks.Supplier : "Supplier",
Tasks.tasks.Extortion : "Extortion",
Tasks.tasks.Stirrup : "Stirrup",
Tasks.tasks.FlashDrives1 : "What's on the Flash Drive?",
Tasks.tasks.GoldenSwag : "Golden Swag",
Tasks.tasks.Chem1 : "Chemical",
Tasks.tasks.Chem2 : "Chemical",
Tasks.tasks.Chem3 : "Chemical",
Tasks.tasks.Chem4 : "Chemical",
Tasks.tasks.Vit1 : "Vitamins",
Tasks.tasks.Vit2 : "Vitamins",
Tasks.tasks.FFtW1 : "Friend from the West",
Tasks.tasks.FFtW2 : "Friend from the West",
Tasks.tasks.LL1 : "Lend-Lease",
Tasks.tasks.Setup : "Setup",
Tasks.tasks.Informed : "Informed Means Armed",
Tasks.tasks.Chumming : "Chumming",
Tasks.tasks.Bullshit : "Bullshit",
Tasks.tasks.Flint : "Flint",
Tasks.tasks.KindaSabotage : "Kind of Sabotage",
Tasks.tasks.RiggedGame : "Rigged Game",
Tasks.tasks.SafeCorridor : "Safe Corridor",
Tasks.tasks.LongRoad : "Long Road",
Tasks.tasks.MissingCargo : "Missing Cargo",
Tasks.tasks.Fishing : "Fishing Gear",
Tasks.tasks.TigrSafari : "Tigr Safari",
Tasks.tasks.ScrapMetal : "Scrap Metal",
Tasks.tasks.EagleEye : "Eagle Eye",
Tasks.tasks.Blueberry1 : "Humanitarian Supplies",
Tasks.tasks.Cult1 : "The Cult",
Tasks.tasks.Cult2 : "The Cult",
Tasks.tasks.SpaTour1 : "Spa Tour",
Tasks.tasks.SpaTour2 : "Spa Tour",
Tasks.tasks.SpaTour3 : "Spa Tour",
Tasks.tasks.SpaTour4 : "Spa Tour",
Tasks.tasks.SpaTour5 : "Spa Tour",
Tasks.tasks.SpaTour6 : "Spa Tour",
Tasks.tasks.SpaTour7 : "Spa Tour",
Tasks.tasks.Cargo1 : "Cargo X",
Tasks.tasks.Cargo2 : "Cargo X",
Tasks.tasks.Cargo3 : "Cargo X",
Tasks.tasks.WetJob1 : "Wet Job",
Tasks.tasks.WetJob2 : "Wet Job",
Tasks.tasks.WetJob3 : "Wet Job",
Tasks.tasks.WetJob4 : "Wet Job",
Tasks.tasks.WetJob5 : "Wet Job",
Tasks.tasks.WetJob6 : "Wet Job",
Tasks.tasks.TheGuide : "The Guide",
Tasks.tasks.Samples : "Samples",
Tasks.tasks.Terragroup : "Terragroup Employee",
Tasks.tasks.LL2 : "Lend-Lease",
Tasks.tasks.Blueberry2 : "Peacekeeping Mission",
Tasks.tasks.ClassTech : "Classified Technologies",
Tasks.tasks.RevisReserve : "Revision",
Tasks.tasks.Cargo4 : "Cargo X",
Tasks.tasks.Insomnia : "Insomnia",
Tasks.tasks.Overpopulation : "Overpopulation",
Tasks.tasks.RevisLighthouse : "Revision",
Tasks.tasks.Intro : "Introduction",
Tasks.tasks.GS1 : "Gunsmith",
Tasks.tasks.GS2 : "Gunsmith",
Tasks.tasks.GS3 : "Gunsmith",
Tasks.tasks.GS4 : "Gunsmith",
Tasks.tasks.GS5 : "Gunsmith",
Tasks.tasks.GS6 : "Gunsmith",
Tasks.tasks.GS7 : "Gunsmith",
Tasks.tasks.GS8 : "Gunsmith",
Tasks.tasks.GS9 : "Gunsmith",
Tasks.tasks.GS10 : "Gunsmith",
Tasks.tasks.GS11 : "Gunsmith",
Tasks.tasks.GS12 : "Gunsmith",
Tasks.tasks.GS13 : "Gunsmith",
Tasks.tasks.GS14 : "Gunsmith",
Tasks.tasks.GS15 : "Gunsmith",
Tasks.tasks.GS16 : "Gunsmith",
Tasks.tasks.GS17 : "Gunsmith",
Tasks.tasks.GS18 : "Gunsmith",
Tasks.tasks.GS19 : "Gunsmith",
Tasks.tasks.GS20 : "Gunsmith",
Tasks.tasks.GS21 : "Gunsmith",
Tasks.tasks.GS22 : "Gunsmith",
Tasks.tasks.Signal1 : "Signal",
Tasks.tasks.Insider : "Insider",
Tasks.tasks.Signal2 : "Signal",
Tasks.tasks.Scout : "Scout",
Tasks.tasks.SurpGoods : "Surplus Goods",
Tasks.tasks.BackDoor : "Back Door",
Tasks.tasks.Signal3 : "Signal",
Tasks.tasks.Signal4 : "Signal",
Tasks.tasks.Farming1 : "Farming",
Tasks.tasks.Farming2 : "Farming",
Tasks.tasks.BadHabit : "Bad Habit",
Tasks.tasks.Farming3 : "Farming",
Tasks.tasks.Farming4 : "Farming",
Tasks.tasks.PsychoSniper : "Psycho Sniper",
Tasks.tasks.ShooterBorn : "A Shooter Born In Heaven",
Tasks.tasks.Fertilizers : "Fertilizers",
Tasks.tasks.Import : "Import",
Tasks.tasks.ChemCloset : "Chemical Closet",
Tasks.tasks.CorpoSecret : "Corporate Secrets",
Tasks.tasks.EnergyCrisis : "Energy Crisis",
Tasks.tasks.Broadcast1 : "Broadcast",
Tasks.tasks.OnlyBusiness : "Only Business",
Tasks.tasks.MUGA : "Make ULTRA Great Again",
Tasks.tasks.BigSale : "Big Sale",
Tasks.tasks.FuelMatter : "A Fuel Matter",
Tasks.tasks.Inventory : "Inventory Check",
Tasks.tasks.Blood1 : "The Blood of War",
Tasks.tasks.DressedtoKill : "Dressed to Kill",
Tasks.tasks.Gratitude : "Gratitude",
Tasks.tasks.Delivery : "Hot Delivery",
Tasks.tasks.Scav : "Scavenger",
Tasks.tasks.SalesNight : "Sales Night",
Tasks.tasks.Data1 : "Database",
Tasks.tasks.Data2 : "Database",
Tasks.tasks.Minibus : "Minibus",
Tasks.tasks.Sew1 : "Sew it Good",
Tasks.tasks.Blood2 : "The Blood of War",
Tasks.tasks.Blood3 : "The Blood of War",
Tasks.tasks.Sew2 : "Sew it Good",
Tasks.tasks.KeytoSuccess : "The Key to Success",
Tasks.tasks.NoFuss : "No Fuss Needed",
Tasks.tasks.Supervisor : "Supervisor",
Tasks.tasks.Sew3 : "Sew it Good",
Tasks.tasks.LHinaC1 : "Living High is Not a Crime",
Tasks.tasks.LHinaC2 : "Living High is Not a Crime",
Tasks.tasks.Sew4 : "Sew it Good",
Tasks.tasks.Charisma : "Charisma Brings Success",
Tasks.tasks.Acquaintance : "Acquaintance",
Tasks.tasks.Unprotected : "The Survivalist Path",
Tasks.tasks.Thrifty : "The Survivalist Path",
Tasks.tasks.Zhivchik : "The Survivalist Path",
Tasks.tasks.Wounded : "The Survivalist Path",
Tasks.tasks.ToughGuy : "The Survivalist Path",
Tasks.tasks.CourtesyVisit : "Courtesy Visit",
Tasks.tasks.Nostalgia : "Nostalgia",
Tasks.tasks.Junkie : "The Survivalist Path",
Tasks.tasks.Eagle : "The Survivalist Path",
Tasks.tasks.Medic : "The Survivalist Path",
Tasks.tasks.Ambulance : "Ambulance",
Tasks.tasks.SecurePerimeter : "The Huntsman Path",
Tasks.tasks.Reserve : "Reserve",
Tasks.tasks.ForestCleaning : "The Huntsman Path",
Tasks.tasks.Controller : "The Huntsman Path",
Tasks.tasks.EvilWatchman : "The Huntsman Path",
Tasks.tasks.FishingPlace : "Fishing Place",
Tasks.tasks.Trophy : "The Huntsman Path",
Tasks.tasks.Justice : "The Huntsman Path",
Tasks.tasks.Sellout : "The Huntsman Path",
Tasks.tasks.WoodsKeeper : "The Huntsman Path",
Tasks.tasks.HuntingTrip : "Hunting Trip",
Tasks.tasks.FactoryChief : "The Huntsman Path",
Tasks.tasks.Eraser1 : "The Huntsman Path",
Tasks.tasks.Eraser2 : "The Huntsman Path",
Tasks.tasks.TarkShoot1 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot2 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot3 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot4 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot5 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot6 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot7 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot8 : "The Tarkov Shooter",
Tasks.tasks.FlashDrives2 : "Shady Business",
Tasks.tasks.Sadist : "The Huntsman Path",
Tasks.tasks.PestControl : "Pest Control",
Tasks.tasks.Hermit : "Hermit",
Tasks.tasks.Outcasts : "The Huntsman Path",
Tasks.tasks.StrayDogs : "Stray Dogs",
Tasks.tasks.Sausage : "The Delicious Sausage",
Tasks.tasks.OldFiresteel: "",
Tasks.tasks.AntiqueAxe: "",
Tasks.tasks.AntiqueBook: "",
Tasks.tasks.FireKlean: "",
Tasks.tasks.GoldenCock: "",
Tasks.tasks.Yeehaw: "",
Tasks.tasks.BeardOil: "",
Tasks.tasks.GPhone: "",
Tasks.tasks.DevilDog: "",
Tasks.tasks.Sprats: "",
Tasks.tasks.Mustache: "",
Tasks.tasks.Kotton: "",
Tasks.tasks.LupoBeans: "",
Tasks.tasks.Pestily: "",
Tasks.tasks.Raven: "",
Tasks.tasks.Shroud: "",
Tasks.tasks.Veritas: "",
Tasks.tasks.Tea: "",
Tasks.tasks.Smoke: "",
Tasks.tasks.Armband: "",
Tasks.tasks.RatCola: "",
Tasks.tasks.LootLord: "",
Tasks.tasks.WZWallet: "",
Tasks.tasks.RatPoison: "",
Tasks.tasks.Missam: "",
Tasks.tasks.Cassette: "",
Tasks.tasks.BakeEzy: "",
Tasks.tasks.JohnB: "",
Tasks.tasks.GloriousE: "",
Tasks.tasks.RedBeard: "",
Tasks.tasks.RedPACA: "",
Tasks.tasks.Gingy: "",
Tasks.tasks.Egg: "",
Tasks.tasks.PressPass: "",
Tasks.tasks.Axel: "",
Tasks.tasks.BEARBuddy: "",
}
const TaskPart:= {
Tasks.tasks.Debut: "",
Tasks.tasks.Search: "",
Tasks.tasks.Checking: "",
Tasks.tasks.Shootout: "",
Tasks.tasks.PastDelivery: "",
Tasks.tasks.BPDepot: "",
Tasks.tasks.Bunker1: "Part 1",
Tasks.tasks.Bunker2: "Part 2",
Tasks.tasks.BadRep: "",
Tasks.tasks.IceCream: "",
Tasks.tasks.Renegades: "",
Tasks.tasks.Documents: "",
Tasks.tasks.Postman1: "Part 1",
Tasks.tasks.ShakingupTeller: "",
Tasks.tasks.Punisher1: "Part 1",
Tasks.tasks.Punisher2: "Part 2",
Tasks.tasks.Punisher3: "Part 3",
Tasks.tasks.Punisher4: "Part 4",
Tasks.tasks.Punisher5: "Part 5",
Tasks.tasks.Punisher6: "Part 6",
Tasks.tasks.Anesthesia: "",
Tasks.tasks.Grenadier: "",
Tasks.tasks.TestDrive1: "Part 1",
Tasks.tasks.Mediator: "",
Tasks.tasks.PolikhimHobo: "",
Tasks.tasks.Regulated: "",
Tasks.tasks.BigCustomer: "",
Tasks.tasks.Intimidator: "",
Tasks.tasks.EasyJob1: "Part 1",
Tasks.tasks.EasyJob2: "Part 2",
Tasks.tasks.Recon: "",
Tasks.tasks.Shortage: "",
Tasks.tasks.Aq1: "Part 1",
Tasks.tasks.Aq2: "Part 2",
Tasks.tasks.Gasan1: "Part 1",
Tasks.tasks.Gasan2: "Part 2",
Tasks.tasks.Painkill: "",
Tasks.tasks.Pharm: "",
Tasks.tasks.DHistory: "",
Tasks.tasks.Car: "",
Tasks.tasks.Supply: "",
Tasks.tasks.HCP1: "Part 1",
Tasks.tasks.HCP2: "Part 2",
Tasks.tasks.HCP3: "Part 3",
Tasks.tasks.HCP4: "Part 4",
Tasks.tasks.Athlete: "",
Tasks.tasks.PClinic: "",
Tasks.tasks.HCP5: "Part 5",
Tasks.tasks.Decontam: "",
Tasks.tasks.Wares: "",
Tasks.tasks.Coll1: "Part 1",
Tasks.tasks.Coll2: "Part 2",
Tasks.tasks.Coll3: "Part 3",
Tasks.tasks.Postman2: "Part 2",
Tasks.tasks.Curiosity: "",
Tasks.tasks.Crisis: "",
Tasks.tasks.Seaside: "",
Tasks.tasks.LostContact: "",
Tasks.tasks.Trafficking: "",
Tasks.tasks.Supplier: "",
Tasks.tasks.Extortion: "",
Tasks.tasks.Stirrup: "",
Tasks.tasks.FlashDrives1: "",
Tasks.tasks.GoldenSwag: "",
Tasks.tasks.Chem1: "Part 1",
Tasks.tasks.Chem2: "Part 2",
Tasks.tasks.Chem3: "Part 3",
Tasks.tasks.Chem4: "Part 4",
Tasks.tasks.Vit1: "Part 1",
Tasks.tasks.Vit2: "Part 2",
Tasks.tasks.FFtW1: "Part 1",
Tasks.tasks.FFtW2: "Part 2",
Tasks.tasks.LL1: "Part 1",
Tasks.tasks.Setup: "",
Tasks.tasks.Informed: "",
Tasks.tasks.Chumming: "",
Tasks.tasks.Bullshit: "",
Tasks.tasks.Flint: "",
Tasks.tasks.KindaSabotage: "",
Tasks.tasks.RiggedGame: "",
Tasks.tasks.SafeCorridor: "",
Tasks.tasks.LongRoad: "",
Tasks.tasks.MissingCargo: "",
Tasks.tasks.Fishing: "",
Tasks.tasks.TigrSafari: "",
Tasks.tasks.ScrapMetal: "",
Tasks.tasks.EagleEye: "",
Tasks.tasks.Blueberry1: "",
Tasks.tasks.Cult1: "Part 1",
Tasks.tasks.Cult2: "Part 2",
Tasks.tasks.SpaTour1: "Part 1",
Tasks.tasks.SpaTour2: "Part 2",
Tasks.tasks.SpaTour3: "Part 3",
Tasks.tasks.SpaTour4: "Part 4",
Tasks.tasks.SpaTour5: "Part 5",
Tasks.tasks.SpaTour6: "Part 6",
Tasks.tasks.SpaTour7: "Part 7",
Tasks.tasks.Cargo1: "Part 1",
Tasks.tasks.Cargo2: "Part 2",
Tasks.tasks.Cargo3: "Part 3",
Tasks.tasks.WetJob1: "Part 1",
Tasks.tasks.WetJob2: "Part 2",
Tasks.tasks.WetJob3: "Part 3",
Tasks.tasks.WetJob4: "Part 4",
Tasks.tasks.WetJob5: "Part 5",
Tasks.tasks.WetJob6: "Part 6",
Tasks.tasks.TheGuide: "",
Tasks.tasks.Samples: "",
Tasks.tasks.Terragroup: "",
Tasks.tasks.LL2: "Part 2",
Tasks.tasks.Blueberry2: "",
Tasks.tasks.ClassTech: "",
Tasks.tasks.RevisReserve: "Reserve",
Tasks.tasks.Cargo4: "Part 4",
Tasks.tasks.Insomnia: "",
Tasks.tasks.Overpopulation: "",
Tasks.tasks.RevisLighthouse: "Lighthouse",
Tasks.tasks.Intro: "",
Tasks.tasks.GS1: "Part 1",
Tasks.tasks.GS2: "Part 2",
Tasks.tasks.GS3: "Part 3",
Tasks.tasks.GS4: "Part 4",
Tasks.tasks.GS5: "Part 5",
Tasks.tasks.GS6: "Part 6",
Tasks.tasks.GS7: "Part 7",
Tasks.tasks.GS8: "Part 8",
Tasks.tasks.GS9: "Part 9",
Tasks.tasks.GS10: "Part 10",
Tasks.tasks.GS11: "Part 11",
Tasks.tasks.GS12: "Part 12",
Tasks.tasks.GS13: "Part 13",
Tasks.tasks.GS14: "Part 14",
Tasks.tasks.GS15: "Part 15",
Tasks.tasks.GS16: "Part 16",
Tasks.tasks.GS17: "Part 17",
Tasks.tasks.GS18: "Part 18",
Tasks.tasks.GS19: "Part 19",
Tasks.tasks.GS20: "Part 20",
Tasks.tasks.GS21: "Part 21",
Tasks.tasks.GS22: "Part 22",
Tasks.tasks.Signal1: "Part 1",
Tasks.tasks.Insider: "",
Tasks.tasks.Signal2: "Part 2",
Tasks.tasks.Scout: "",
Tasks.tasks.SurpGoods: "",
Tasks.tasks.BackDoor: "",
Tasks.tasks.Signal3: "Part 3",
Tasks.tasks.Signal4: "Part 4",
Tasks.tasks.Farming1: "Part 1",
Tasks.tasks.Farming2: "Part 2",
Tasks.tasks.BadHabit: "",
Tasks.tasks.Farming3: "Part 3",
Tasks.tasks.Farming4: "Part 4",
Tasks.tasks.PsychoSniper: "",
Tasks.tasks.ShooterBorn: "",
Tasks.tasks.Fertilizers: "",
Tasks.tasks.Import: "",
Tasks.tasks.ChemCloset: "",
Tasks.tasks.CorpoSecret: "",
Tasks.tasks.EnergyCrisis: "",
Tasks.tasks.Broadcast1: "",
Tasks.tasks.OnlyBusiness: "",
Tasks.tasks.MUGA: "",
Tasks.tasks.BigSale: "",
Tasks.tasks.FuelMatter: "",
Tasks.tasks.Inventory: "",
Tasks.tasks.Blood1: "Part 1",
Tasks.tasks.DressedtoKill: "",
Tasks.tasks.Gratitude: "",
Tasks.tasks.Delivery: "",
Tasks.tasks.Scav: "",
Tasks.tasks.SalesNight: "",
Tasks.tasks.Data1: "Part 1",
Tasks.tasks.Data2: "Part 2",
Tasks.tasks.Minibus: "",
Tasks.tasks.Sew1: "Part 1",
Tasks.tasks.Blood2: "Part 2",
Tasks.tasks.Blood3: "Part 3",
Tasks.tasks.Sew2: "Part 2",
Tasks.tasks.KeytoSuccess: "",
Tasks.tasks.NoFuss: "",
Tasks.tasks.Supervisor: "",
Tasks.tasks.Sew3: "Part 3",
Tasks.tasks.LHinaC1: "Part 1",
Tasks.tasks.LHinaC2: "Part 2",
Tasks.tasks.Sew4: "Part 4",
Tasks.tasks.Charisma: "",
Tasks.tasks.Acquaintance: "",
Tasks.tasks.Unprotected: "Unprotected but Dangerous",
Tasks.tasks.Thrifty: "Thrifty",
Tasks.tasks.Zhivchik: "Zhivchik",
Tasks.tasks.Wounded: "Wounded Beast",
Tasks.tasks.ToughGuy: "Tough Guy",
Tasks.tasks.CourtesyVisit: "",
Tasks.tasks.Nostalgia: "",
Tasks.tasks.Junkie: "Junkie",
Tasks.tasks.Eagle: "Eagle-Owl",
Tasks.tasks.Medic: "Combat Medic",
Tasks.tasks.Ambulance: "",
Tasks.tasks.SecurePerimeter: "Secure Perimeter",
Tasks.tasks.Reserve: "",
Tasks.tasks.ForestCleaning: "Forest Cleaning",
Tasks.tasks.Controller: "Controller",
Tasks.tasks.EvilWatchman: "Evil Watchman",
Tasks.tasks.FishingPlace: "",
Tasks.tasks.Trophy: "Trophy",
Tasks.tasks.Justice: "Justice",
Tasks.tasks.Sellout: "Sellout",
Tasks.tasks.WoodsKeeper: "Woods Keeper",
Tasks.tasks.HuntingTrip: "",
Tasks.tasks.FactoryChief: "Factory Chief",
Tasks.tasks.Eraser1: "Eraser - Part 1",
Tasks.tasks.Eraser2: "Eraser - Part 2",
Tasks.tasks.TarkShoot1: "Part 1",
Tasks.tasks.TarkShoot2: "Part 2",
Tasks.tasks.TarkShoot3: "Part 3",
Tasks.tasks.TarkShoot4: "Part 4",
Tasks.tasks.TarkShoot5: "Part 5",
Tasks.tasks.TarkShoot6: "Part 6",
Tasks.tasks.TarkShoot7: "Part 7",
Tasks.tasks.TarkShoot8: "Part 8",
Tasks.tasks.FlashDrives2: "",
Tasks.tasks.Sadist: "Sadist",
Tasks.tasks.PestControl: "",
Tasks.tasks.Hermit: "",
Tasks.tasks.Outcasts: "Outcasts",
Tasks.tasks.StrayDogs: "",
Tasks.tasks.Sausage: "",
Tasks.tasks.OldFiresteel: "",
Tasks.tasks.AntiqueAxe: "",
Tasks.tasks.AntiqueBook: "",
Tasks.tasks.FireKlean: "",
Tasks.tasks.GoldenCock: "",
Tasks.tasks.Yeehaw: "",
Tasks.tasks.BeardOil: "",
Tasks.tasks.GPhone: "",
Tasks.tasks.DevilDog: "",
Tasks.tasks.Sprats: "",
Tasks.tasks.Mustache: "",
Tasks.tasks.Kotton: "",
Tasks.tasks.LupoBeans: "",
Tasks.tasks.Pestily: "",
Tasks.tasks.Raven: "",
Tasks.tasks.Shroud: "",
Tasks.tasks.Veritas: "",
Tasks.tasks.Tea: "",
Tasks.tasks.Smoke: "",
Tasks.tasks.Armband: "",
Tasks.tasks.RatCola: "",
Tasks.tasks.LootLord: "",
Tasks.tasks.WZWallet: "",
Tasks.tasks.RatPoison: "",
Tasks.tasks.Missam: "",
Tasks.tasks.Cassette: "",
Tasks.tasks.BakeEzy: "",
Tasks.tasks.JohnB: "",
Tasks.tasks.GloriousE: "",
Tasks.tasks.RedBeard: "",
Tasks.tasks.RedPACA: "",
Tasks.tasks.Gingy: "",
Tasks.tasks.Egg: "",
Tasks.tasks.PressPass: "",
Tasks.tasks.Axel: "",
Tasks.tasks.BEARBuddy: "",
}

const TaskDescripts:= {
Tasks.tasks.Debut: "• Eliminate 5 Scavs\n• Hand in 5 MP-133 Shotguns",
Tasks.tasks.Search: "• Find the Missing Convoy on Woods\n• Find the USEC camp on Woods\n• Survive and Extract",
Tasks.tasks.Checking: "• Find the Bronze Pocket Watch on Customs\n• Hand the quest item over to Prapor",
Tasks.tasks.Shootout: "• Eliminate 15 Scavs on Woods",
Tasks.tasks.PastDelivery: "• Obtain Secure Folder 0022 in Big Red on Customs\n• Stash the folder in the Factory break room\n• Survive and Extract",
Tasks.tasks.BPDepot: "• Mark all four fuel tanks with MS2000 Markers on Customs\n• Survive and Extract\n",
Tasks.tasks.Bunker1: "• Find the Underground Bunker on Reserve\n• 2 Bronze Lions\n• 2 Bronze Lions\n",
Tasks.tasks.Bunker2: "• Find the hermetic door leading to White Bishop\n• Find one of the hermetic doors leading to Black Bishop\n• Find one of the hermetic doors leading to Black Pawn\n• Find one of the hermetic doors leading to White Pawn\n• Find one of the hermetic doors leading to White King\n• Survive and Extract",
Tasks.tasks.BadRep: "• Obtain Secure Folder 0031 in the Bunkhouse next to Big Skeleton on Customs\n• Hand the folder over to Prapor",
Tasks.tasks.IceCream: "• Find 3 6L31 60-round 5.45x39mm Magazines in raid\n• Hand the magazines over to Prapor",
Tasks.tasks.Renegades: "• Eliminate 5 Raiders in the Command Bunker on Reserve",
Tasks.tasks.Documents: "• Find Documents №1-3 on Reserve\n• Hand the quest items over to Prapor",
Tasks.tasks.Postman1: "• Obtain the letter on the messenger's body on Factory\n• Survive and Extract\n• Hand the quest item over to Therapist",
Tasks.tasks.ShakingupTeller: "• Obtain the Bank Case in Room 203 in 3-Story Dorms on Customs\n• Hand the quest item over to Prapor",
Tasks.tasks.Punisher1: "• Eliminate 15 Scavs with an AKM series weapon on Shoreline",
Tasks.tasks.Punisher2: "• Eliminate 15 Scavs with a suppressed weapon on Reserve\n• Find 7 Half-Masks in raid\n• Hand the Half-Masks over to Prapor",
Tasks.tasks.Punisher3: "• Eliminate 25 Scavs with an AKS-74U series weapon on Customs",
Tasks.tasks.Punisher4: "• Eliminate 10 Scavs while using a 12ga shotgun on Lighthouse\n• Eliminate 10 PMCs while wearing a Balaclava and Scav Vest on Lighthouse\n• Find 5 Brown Scav Knives in raid\n• Hand the Knives over to Prapor",
Tasks.tasks.Punisher5: "• Find 1 AK-74N in raid\n• Find 1 Colt M4A1 in raid\n• Find 2 PM pistols in raid\n• Hand the weapons over to Prapor\n• Eliminate 10 PMCs while wearing a PACA and 6B47 helmet",
Tasks.tasks.Punisher6: "• Eliminate 15 PMCs with an SVDS rifle (excluding Factory)\n• Find 7 Bear Dogtags and 7 USEC Dogtags in raid\n• Hand all the Dogtags over to Prapor",
Tasks.tasks.Anesthesia: "• Mark all 3 trading posts with an MS2000 Marker on Shoreline\n• Survive and Extract",
Tasks.tasks.Grenadier: "• Eliminate 8 PMCs with Hand Grenades",
Tasks.tasks.TestDrive1: "• Eliminate 5 PMCs from over 60 meters away with an M1A utilizing a Hybrid 46 Suppressor and Schmidt and Bender PM II 1-8x24 scope",
Tasks.tasks.Mediator: "• Reach Max Loyalty with every trader (Other than Fence and the fat bastard)",
Tasks.tasks.PolikhimHobo: "• Eliminate 25 Scavs on Customs",
Tasks.tasks.Regulated: "• Find 1 6-STEN-140-M Battery in raid\n• Find 5 OFZ 30x160mm Shells in raid\n• Hand the specified items over to Sidorovi- oh uh Prapor whoops haha",
Tasks.tasks.BigCustomer: "• Mark the Van inside Chemical on Customs\n• Survive and Extract\nCOMPLETING THIS QUEST LOCKS OFF \"OUT OF CURIOSITY\" AND \"CHEMICAL\"",
Tasks.tasks.Intimidator: "• Eliminate 40 Scavs with headshots",
Tasks.tasks.EasyJob1: "• Locate and Mark the Helicopter in the Water Treatment Plant on Lighthouse\n• Survive and Extract",
Tasks.tasks.EasyJob2: "• Eliminate any 20 Targets around the Helicopter in the Water Treatment Plant on Lighthouse",
Tasks.tasks.Recon: "• Recon the roofs of the 3 Buildings in the Water Treatment Plant on Lighthouse\n• Survive and Extract",
Tasks.tasks.Shortage: "• Find 3 Salewas in raid\n• Hand the Salewas over to Therapist",
Tasks.tasks.Aq1: "• Find the Water hidden inside 2-Story Dorms on Customs\n• Survive and Extract",
Tasks.tasks.Aq2: "• Eliminate 15 Scavs on Customs",
Tasks.tasks.Gasan1: "• Find 1 Gas Analyzer in raid\n• Hand the Gas Analyzer over to Therapist",
Tasks.tasks.Gasan2: "• Okay now do it again but twice\n• Don't you love game design",
Tasks.tasks.Painkill: "• Find 4 Morphine Pens in raid\n• Hand the Fent over to Therapist",
Tasks.tasks.Pharm: "• Obtain the case inside Room 114 of 3-Story Dorms on Customs\n• Hand the case over to Therapist",
Tasks.tasks.DHistory: "• Find Medical Records #1 and #2 on Reserve\n• Hand the Records over to Therapist",
Tasks.tasks.Car: "• Find 4 Car Batteries in raid\n• Find 8 Spark Plugs in raid\n• Hand the specified items over to Therapist",
Tasks.tasks.Supply: "• Find Secure Folder 0052 on Woods\n• Hand the folder over to Therapist\nCOMPLETING THIS QUEST LOCKS OFF \"KIND OF SABOTAGE\"",
Tasks.tasks.HCP1: "• Mark the three Ambulances with MS2000 Markers on Shoreline\n• Survive and Extract",
Tasks.tasks.HCP2: "• Obtain Secure Folder 0060 in Resort W306 on Shoreline\n• Hand the folder over to Therapist",
Tasks.tasks.HCP3: "• Lick the blood off of the sinking van on Woods\n• Prove to Therapist that you did, in fact, lick the van",
Tasks.tasks.HCP4: "• Reach Health Level 4",
Tasks.tasks.Athlete: "• Reach Health Level 10",
Tasks.tasks.PClinic: "• Find 1 Opthalmascope in raid\n• Find 1 LEDX in raid \n• Hand your cumulative ₽1,000,000 over to Therapist and weep",
Tasks.tasks.HCP5: "• Convince your buddies that you really need to do this quest please help\n• Stash 3 Blue Gunpowder in the Breach Room in Office on Factory at Night",
Tasks.tasks.Decontam: "• Eliminate 40 Scavs on Interchange from less than 60 meters while wearing a Respirator or Gas Mask",
Tasks.tasks.Wares: "• Find 15 Small Tushonkas in raid\n• Hand the stew over to Therapist",
Tasks.tasks.Coll1: "• Locate the corpses at Pier, Cottages, and Resort on Shoreline in one raid\n• Survive and Extract",
Tasks.tasks.Coll2: "• Find Sanitar's CMS kit and Opthalmascope on Shoreline\n• Hand the medical gear over to Therapist",
Tasks.tasks.Coll3: "• Do not kill Sanitar\n• Find 10 Labs Access cards in raid\n• Find 1 AHF1-M and 1 3-(b-TG) in raid\n• Hand the cards and stims over to Therapist\nCOMPLETING THIS QUEST LOCKS OFF \"THE HUNTSMAN PATH - SADIST\"",
Tasks.tasks.Postman2: "• Hand the letter from Prapor's messenger over to Therapist",
Tasks.tasks.Curiosity: "• Mark the Van inside Chemical on Customs\n• Survive and Extract\nCOMPLETING THIS QUEST LOCKS OFF \"BIG CUSTOMER\" AND \"CHEMICAL\"",
Tasks.tasks.Crisis: "• Find 3 Portable Defibrillators in raid\n• Find 3 Opthalmascopes in raid\n• Find 2 LEDXes in raid\n• Find 20 Assorted Piles of Meds in raid\n• Find 10 Flintstone Multivitamins in raid\n• Hand all the specified items over to Therapist\n• This quest costs an unreasonable amount of money. weep once more.",
Tasks.tasks.Seaside: "• Find the informant's briefcase on Lighthouse\n• Hand the briefcase over to Therapist",
Tasks.tasks.LostContact: "• Find the lost group at the chalet on Lighthouse\n• Survive and Extract",
Tasks.tasks.Trafficking: "• Locate the Hidden Drug Lab on Lighthouse\n• Stash a Wifi Camera in the Drug Lab",
Tasks.tasks.Supplier: "• Hand 1 Module-3M armor found in raid over to Skier\n• Hand 1 TOZ-106 found in raid over to Skier",
Tasks.tasks.Extortion: "• Find Secure Folder 0048 on Customs\n• Hand the folder over to Skier",
Tasks.tasks.Stirrup: "• Eliminate 3 PMCs with pistols",
Tasks.tasks.FlashDrives1: "• Find 2 Secure Flash Drives in raid\n• Hand the flash drives over to Skier.\n• Keep collecting them.",
Tasks.tasks.GoldenSwag: "• Find the Golden Zibbo lighter in Dorms 303 on Customs\n• Stash the lighter in the bunkhouse trailer adjacent to Big Red on Customs",
Tasks.tasks.Chem1: "Obtain Secure Folder 0013 on Customs\n• Buy the Dorms 220 key off of the flea market\n• Hand both items over to Skier",
Tasks.tasks.Chem2: "• Find the Sliderkey and Sealed Terragroup letter in Room 220 of 3-Story Dorms on Customs\n• Hand the quest items over to Skier",
Tasks.tasks.Chem3: "• Find the chemical syringe in the breach room in Office on Factory\n• Hand the syringe over to Skier",
Tasks.tasks.Chem4: "• Mark the Van inside Chemical on Customs\n• Survive and Extract\nCOMPLETING THIS QUEST LOCKS OFF \"BIG CUSTOMER\" AND \"OUT OF CURIOSITY\"",
Tasks.tasks.Vit1: "• Find the first chemical container on Shoreline\n• Find the second and third chemical containers on Interchange\n• Hand the containers over to Skier",
Tasks.tasks.Vit2: "• Find 4 Respirators in raid\n• Find 3 Bloodsets in raid\n• Hand the specified items over to Skier",
Tasks.tasks.FFtW1: "• Eliminate 7 USEC PMCs\n• Find 7 USEC PMC dogtags\n• Hand the dogtags over to Skier",
Tasks.tasks.FFtW2: "• Hand $6000 over to Skier\n• Because Fuck You, that's why",
Tasks.tasks.LL1: "• Find the first Motor Controller and Gyroscope on Woods\n• Find the second and third Motor Controllers and the second Gyroscope on Shoreline\n• Take a fuckin' guess.",
Tasks.tasks.Setup: "• Eliminate 15 PMCs with an MP-series Shotgun (NOT THE SAWED-OFF) while wearing a Ushanka and Scav Vest on Customs",
Tasks.tasks.Informed: "• Stash a Wifi Camera at the Dock on Woods, the road on Customs, and across from KIBA on Interchange\n• Please Consult the Wiki for further Guidance.\n• I cannot be asked to program more systems for this already bloated and shitty app",
Tasks.tasks.Chumming: "• Stash 3 Golden Neck Chains (9 total) under the Mattress in Generic on Interchange, the Microwave on floor 3 of Dorms on Customs, and the Middle Wooden Cabin at Sawmill on Woods\n• Eliminate 5 PMCs between 22:00 and 10:00 on Interchange",
Tasks.tasks.Bullshit: "• Do not kill any scavs on Customs.\n• Find the False Flash Drive in the trunk of a car on the Bridge on Customs\n• Stash the flash drive, a Roler wristwatch, and an SV-98 opposite the floor 3 stairs of Dorms on Customs",
Tasks.tasks.Flint: "• Reach Stress Resistance Level 5",
Tasks.tasks.KindaSabotage: "• Hand Secure Folder 0052 over to Skier\nCOMPLETING THIS QUEST LOCKS OFF \"SUPPLY PLANS\"",
Tasks.tasks.RiggedGame: "• Mark the boxes at Pier, Cottages, and Resort with MS2000 Markers on Shoreline\n• Survive and Extract",
Tasks.tasks.SafeCorridor: "• Eliminate 10 Scavs in the underground warehouse on Reserve",
Tasks.tasks.LongRoad: "• Eliminate 15 Scavs along the main road on Lighthouse",
Tasks.tasks.MissingCargo: "• Find the Informant's Intel Folder on Lighthouse\n• Hand the folder over to Skier",
Tasks.tasks.Fishing: "• Stash an SV-98 and a Multitool at the Boat on Shoreline\n• Survive and Extract",
Tasks.tasks.TigrSafari: "• Find and Mark all 3 Tigr vehicles with MS2000 Markers on Customs\n• Survive and Extract",
Tasks.tasks.ScrapMetal: "• Find and Mark all 3 Tanks with MS2000 Markers on Shoreline\n• Survive and Extract",
Tasks.tasks.EagleEye: "• Find the SAS Disks from both crashed UAVs on Shoreline\n• Hand the disks over to Peacekeeper",
Tasks.tasks.Blueberry1: "• Find and Mark both trucks with MS2000 Markers on Shoreline\n• Find 5 MREs\n• Hand the MREs over to Peacekeeper\n• Eliminate 15 Scavs while wearing the Blueberry Gear on Shoreline\n• Survive and Extract",
Tasks.tasks.Cult1: "• Find the Missing Informant in the Sunken Village on Shoreline\n• Survive and Extract",
Tasks.tasks.Cult2: "• Mark both Cultist Circles on Woods with MS2000 Markers\n• Mark the Cultist Circle on Shoreline with a MS2000 Marker\n• Check Dorms 314 key price\n• weep.\n• Mark Dorms 314 with an MS2000 Marker",
Tasks.tasks.SpaTour1: "• Headshot 7 Scavs on Shoreline with a 12ga Shotgun",
Tasks.tasks.SpaTour2: "• Mark the Helicopter and Safe Road at Resort on Shoreline with MS2000 Markers\n• Survive and Extract",
Tasks.tasks.SpaTour3: "• Find 1 Small WD-40 in raid\n• Find 2 Clin bottles in raid\n• Find 2 Corrugated Hoses in raid\n• Find 2 Ox bleach bottles in raid\n• Hand the specified items over to Skier",
Tasks.tasks.SpaTour4: "• Locate the Generators in the East and West wings of Resort on Shoreline\n• Survive and Extract",
Tasks.tasks.SpaTour5: "• Find the Sanitarium Key in the Bunker behind Resort on Shoreline\n• Hand the key over to Peacekeeper",
Tasks.tasks.SpaTour6: "• Hand $8000 over to Peacekeeper\n• thousand_raid_stare.mp4",
Tasks.tasks.SpaTour7: "• Find 4 Morphine Pens in raid\n• Find 2 Alkaline cleaners in raid\n• Find 2 Corrugated Hoses in raid\n• Find 2 Propane Tanks in raid\n• Hand the specified items over to Peacekeeper",
Tasks.tasks.Cargo1: "• Find the data in the computer room in East Wing Resort on Shoreline\n• Hand the data over to Peacekeeper",
Tasks.tasks.Cargo2: "• Obtain Secure Folder 0018 in Resort on Shoreline\n• Hand the folder over to Peacekeeper",
Tasks.tasks.Cargo3: "• Find the hidden Terragroup Cargo on Shoreline\n• Survive and Extract",
Tasks.tasks.WetJob1: "• Eliminate 10 Scavs with a Suppressed AR-15 on Shoreline",
Tasks.tasks.WetJob2: "• Find and Mark the Fisherman's Dwelling with a MS2000 Marker on Shoreline\n• Survive and Extract",
Tasks.tasks.WetJob3: "• Find Artyom's Car on Shoreline\n• Survive and Extract",
Tasks.tasks.WetJob4: "• Find the Resort's Tenant List on Shoreline\n• Hand the list over to Peacekeeper",
Tasks.tasks.WetJob5: "• Find information on Artyom's work on Shoreline\n• Hand the information over to Peacekeeper",
Tasks.tasks.WetJob6: "• Reach Sniper Rifles Level 7",
Tasks.tasks.TheGuide: "• Survive and Extract from every map in the game (excluding Ground Zero) without dying",
Tasks.tasks.Samples: "• Find a M.U.L.E. stimulant in raid\n• Find an \"Obdolbos\" cocktail in raid\n• Find a Meldonin stimulant in raid\n• Find an AHF1-M stimulant in raid\n• Find a P22 Stimulant in raid\n• Find an L1 stimulant in raid\n• Find a 3-(b-tg) stimulant in raid\n• Hand over all the stimulants to Peacekeeper",
Tasks.tasks.Terragroup: "• Find Sanitar's workplace in The Lab\n• Find information about Sanitar's work in The Lab\n• Hand the information over to Peacekeeper",
Tasks.tasks.LL2: "• Find 2 Virtex Processors in raid\n• Find 1 CODFM in raid\n• Hand the tech items over to Peacekeeper",
Tasks.tasks.Blueberry2: "• Eliminate 12 Scavs (60 total) with an M4 while wearing Blueberry Gear on Woods, Customs, Interchange, Shoreline, and Streets of Tarkov\n",
Tasks.tasks.ClassTech: "• Find the T-90M Controller Package on Reserve\n• Hand the package over to Peacekeeper",
Tasks.tasks.RevisReserve: "• Find and Mark the four BMP-2s on Reserve with MS2000 Markers\n• Find and Mark the first LAV III on Reserve with an MS2000 Marker\n• Find the second LAV III and the T-90 on Reserve",
Tasks.tasks.Cargo4: "• Find and Mark the Terragroup container on the Shores of Lighthouse with an MS2000 Marker\n• Survive and Extract",
Tasks.tasks.Insomnia: "• Eliminate 30 PMCs between 22:00 and 05:00 on any map other than Factory and The Lab",
Tasks.tasks.Overpopulation: "• Eliminate 12 Scavs at the Cottages on Lighthouse",
Tasks.tasks.RevisLighthouse: "• Find and Mark the two BRDMs on Lighthouse with MS2000 Markers\n• Find and Mark the two Strykers on Lighthouse with MS2000 Markers",
Tasks.tasks.Intro: "• Find Jaeger's camp on Woods\n• Find the encrypted message on Woods\n• Hand the message over to Mechanic",
Tasks.tasks.GS1: "• Modify an MP-133 with the following parameters:\n• Laser Designator\n• Extended Magazine\n• >47 Ergo\n• <850 Sum Recoil",
Tasks.tasks.GS2: "• Modify an AKS-74u with the following parameters:\n• B-11 Handguard\n• 60rnd Magazine\n• 6 Slots Maximum\n• >58 Ergo\n• <550m Sum Recoil\n• >=100m Sighting Range",
Tasks.tasks.GS3: "• Modify an MP5 with the following parameters:\n• 50rnd Magazine\n• Suppressed\n• Flashlight\n• >45 Ergo\n• <210 Sum Recoil\n• >200m Sighting Range\n• 4kg Maximum Weight",
Tasks.tasks.GS4: "• Modify an OP-SKS with the following parameters:\n• Extended Magazine\n• Scope\n• Suppressed\n• >35 Ergo\n• <350 Sum Recoil",
Tasks.tasks.GS5: "• Modify an M870 with the following parameters:\n• MOE Handguard\n• Laser/Light\n• Foregrip\n• >60 Ergo\n• <500 Sum Recoil",
Tasks.tasks.GS6: "• Modify an AKM with the following parameters:\n• Suppressed\n• Shift Foregrip\n• 30rnd Magpul Magazine\n• >40 Ergo\n• <400 Sum Recoil\n• >=800m Sighting Range",
Tasks.tasks.GS7: "• Modify an M4A1 with the following parameters:\n• Suppressed\n• 60rnd Magazine\n• >47 Ergo\n• <300 Sum Recoil\n• >=800 Sighting Range\n• 3.8kg Max Weight",
Tasks.tasks.GS8: "• Modify an AKS-74N with the following parameters:\n• Full Zenit Furniture\n• AK-12 Magazine\n• Klesch-2lKS\n• 10 Slots Maximum\n• >65 Ergo\n• <275 Sum Recoil",
Tasks.tasks.GS9: "• Modify a P226 with the following parameters:\n• Stainless Elite Slide and Grip\n• Extended Magazine\n• Flashlight\n• >=80 Ergo\n• <=610 Sum Recoil",
Tasks.tasks.GS10: "• Modify an AK-105 with the following parameters:\n• Suppressed\n• 60rnd Magazine\n• 8 Slots Maximum\n• >38 Ergo\n• <500 Sum Recoil\n• 4.8kg Max Weight\n• >800m Sighting Range",
Tasks.tasks.GS11: "• Modify a 9x19 Vector with the following parameters:\n• Mk.5 Modular Rail\n• SFG grip\n• Iron Sights or Optic\n• Suppressed\n• 33rnd Magazine\n• >50 Ergo\n• <230 Sum Recoil\n• >=300m Sighting Range",
Tasks.tasks.GS12: "• Modify a SIG MPX with the following parameters:\n• TD2001 Pistol Grip\n• Annihilator Flash Hider\n• LAS/TAC 2 Flashlight\n• >52 Ergo\n• <225 Sum Recoil\n• >=300m Sighting Range\n• 3.999kg Max Weight",
Tasks.tasks.GS13: "• Modify an RSASS with the following parameters:\n• Suppressed\n• >26 Ergo\n• <300 Sum Recoil\n• >1500m Sighting Range\n• 6.7kg Max Weight",
Tasks.tasks.GS14: "• Modify an HK416A5 with the following parameters:\n• All Attachments are Tan\n• SOCOM56 Suppressor\n• RVG Grip\n• EOTech Optic\n• MOE Pistol Grip\n• UBR GEN2 Stock\n• LA-58/PEQ Tactical Device\n• 30rnd Mag\n• >60 Ergo\n• <300 Sum Recoil\n• 4kg Max Weight",
Tasks.tasks.GS15: "• Modify an AS VAL with the following parameters:\n• GL-SHOCK Stock\n• AN/PEQ-15 Tactical Device\n• NSPU-M Scope\n• 30rnd Magazine\n• >33 Ergo\n• <220 Sum Recoil",
Tasks.tasks.GS16: "• Modify a DVL-10 with the following parameters:\n• Scope\n• Multi-Laser Device\n• >40 Ergo\n• <450 Sum Recoil\n• >2000m Sighting Range\n• 6.7kg Max Weight",
Tasks.tasks.GS17: "• Modify an AK-102 with the following parameters:\n• CRD Device\n• AFG OD Tactical Grip\n• Klesch-2U Flashlight\n• RPK-16 Buffer Tube\n• Circle 10 Magazine\n• >70 Ergo\n• <250 Sum Recoil\n• >=800m Sighting Range",
Tasks.tasks.GS18: "• Modify an AKMN with the following parameters:\n• Black Magpul Furniture + Foregrip\n• Rotor 43 Suppressor\n• EOTech Hybrid Sight\n• >50 Ergo\n• <350 Sum Recoil\n• >500m Sighting Range\n• 5kg Max Weight",
Tasks.tasks.GS19: "• Modify an SVDS with the following parameters:\n• Black UBR GEN2 Stock\n• SAG MK1 Chassis\n• Black MOE Pistol Grip\n• 3-24x42 FFP Scope\n• Suppressed\n• >15 Ergo\n• <500 Sum Recoil\n",
Tasks.tasks.GS20: "• Modify an M1A with the following parameters:\n• M8 Mount\n• ATACR 7-35x56 Scope\n• T-1 Sight\n• LS321 Tactical Device\n• 20rnd Magazine\n• >20 Ergo\n• <400 Sum Recoil\n• 7.3kg Max Weight",
Tasks.tasks.GS21: "• Modify an M700 and M1911 with the following parameters:\n• M700:\n• MOD*X Furniture\n• Scope\n• Suppressed\n• >35 Ergo\n• <500 Sum Recoil\n• >1500 Sighting Range\n• 6kg Max Weight\n• M1911:\n• #423 Grip\n• Anarchy Outdoors Muzzle Brake\n• Tactical Device\n• >200m Sighting Range",
Tasks.tasks.GS22: "• Modify an M4A1 with the following parameters:\n• NT-4 (FDE) Suppressor\n• MK10 Handguard\n• REAP-IR Thermal Scope\n• 60rnd Magazine\n• >40 Ergo\n• <270 Sum Recoil\n• 5kg Max Weight",
Tasks.tasks.Signal1: "• Find both Signal sources\n• Survive and Extract",
Tasks.tasks.Insider: "• Reach Loyalty III with Prapor",
Tasks.tasks.Signal2: "• Find 3 CPUs in raid\n• Find 3 Rechargeable Batteries in raid\n• Find 3 PCBs in raid\n• Find 3 GPhones in raid\n• Hand all specified items over to Mechanic",
Tasks.tasks.Scout: "• Locate all 4 Extracts on Factory\n• Survive and Extract",
Tasks.tasks.SurpGoods: "• Find the MBT System on Reserve\n• Hand the system over to Mechanic",
Tasks.tasks.BackDoor: "• Find the unpowered secret entrance on Reserve\n• Survive and Extract through that entrance",
Tasks.tasks.Signal3: "• Place all 3 Signal Jammers on their specified locations on Shoreline\n• Survive and Extract",
Tasks.tasks.Signal4: "• Reach Memory Level 4",
Tasks.tasks.Farming1: "• Fix both Control Boards with Toolsets on Factory\n• Survive and Extract",
Tasks.tasks.Farming2: "• Find 2 Power Cords in raid\n• Find 4 T-Shaped Plugs in raid\n• Find 2 PCBs in raid\n• Hand all specified items over to Mechanic\n",
Tasks.tasks.BadHabit: "• Find 5 Marlboro Cigarettes in raid\n• Find 5 Strike Cigaretts in raid\n• Find 5 Wilston cigarettes in raid\n• Hand the cigarettes over to Mechanic",
Tasks.tasks.Farming3: "• Find the package of GPUs on Customs\n• Hand the Package over to Mechanic",
Tasks.tasks.Farming4: "• Find 3 GPUs in raid\n• Find 15 CPU Fans in raid\n• Hand the specified items over to Mechanic\n• Yet again, weep.",
Tasks.tasks.PsychoSniper: "• Reach Sniper Rifles Level 10\n• Eliminate 10 PMCs with Bolt-Action Rifles without dying",
Tasks.tasks.ShooterBorn: "• Eliminate 5 PMCs (35 total) with Bolt-Action Headshots on Woods, Reserve, Shoreline, Customs, Lighthouse, Streets of Tarkov, and Interchange	",
Tasks.tasks.Fertilizers: "• Find 5 Bundles of Wire in raid\n• Find 5 Capacitors in raid\n• Hand the specified items over to Mechanic\n• Contemplate why Nikita would put this AFTER Farming 4",
Tasks.tasks.Import: "• Find 1 RFID Reader in raid\n• Find 1 VPX Storage Module in raid\n• Hand the specified items over to Mechanic",
Tasks.tasks.ChemCloset: "• Locate Sanitar's Office in the Health Resort\n• Survive and Extract",
Tasks.tasks.CorpoSecret: "• Find the data in the offices of Buildings 1 and 2 on Lighthouse\n• Hand the data over to Mechanic",
Tasks.tasks.EnergyCrisis: "• Find and Mark the fuel tanks on Lighthouse with an MS2000 Marker\n• Find and Mark the three tanker trucks on Lighthouse with MS2000 Markers",
Tasks.tasks.Broadcast1: "• Locate the hidden recording studio on Lighthouse\n• Place a Signal Jammer inside the studio",
Tasks.tasks.OnlyBusiness: "• Reach Loyalty II with Ragman",
Tasks.tasks.MUGA: "• Eliminate 25 Scavs on Interchange",
Tasks.tasks.BigSale: "• Locate the AVOKADO store on Interchange\n• Locate the KOSTIN store on Interchange\n• Locate the tRend store on Interchange\n• Locate the DINO CLOTHES store on Interchange\n• Locate the TOP BRAND store on Interchange\n• Survive and Extract",
Tasks.tasks.FuelMatter: "• Mark both groups of fuel tanks on Reserve with MS2000 Markers\n• Survive and Extract",
Tasks.tasks.Inventory: "• Locate both arsenals in Black Pawn on Reserve\n• Locate the duty room in Black Pawn on Reserve\n• Locate both arsenals in White Pawn on Reserve\n• Survive and Extract",
Tasks.tasks.Blood1: "• Mark all three fuel trucks on Interchange with MS2000 Markers\n• Survive and Extract",
Tasks.tasks.DressedtoKill: "• Find 2 Cowboy Hats in raid\n• Find 2 Ushankas in raid\n• Hand the hats over to Ragman\n• Why don't we wear hats anymore? It's a real shame.",
Tasks.tasks.Gratitude: "• Stash a Ghost balaclava in the specified place\n• Stash a Shemagh in the specified place\n• Stash some RayBench sunglasses in the specified place\n• Stash a pair of round glasses in the specified place\n• I fucking hate The Beatles",
Tasks.tasks.Delivery: "• Stash 2 Comtac2 Headsets in the specified place\n• Stash 2 6B47 Helmets in the specified place\n• Stash 2 Gzhels in the specified place",
Tasks.tasks.Scav: "• Reach Search Level 9",
Tasks.tasks.SalesNight: "• Survive and Extract on Interchange 7 Times\n• Why? Because fuck you, that's why.\n• That's how all the tasks in this game sound to my friends who dont play Tarkov",
Tasks.tasks.Data1: "• Find the Goshan Cargo Manifests on Interchange\n• Find the OLI Cargo Manifests on Interchange\n• Find the IDEA Cargo Manifests on Interchange\n• Hand the manifests over to Ragman",
Tasks.tasks.Data2: "•  Find the OLI cargo route documents on Interchange\n• Hand the documents over to Ragman",
Tasks.tasks.Minibus: "• Find and Mark all 3 Minibuses on Interchange with MS2000 Markers\n• Survive and Extract",
Tasks.tasks.Sew1: "• Find 1 Shmaska in raid\n• Find 1 Pilgrim in raid\n• Hand the gear over to Ragman",
Tasks.tasks.Blood2: "• Find 4 Fuel Conditioners in raid\n• Turn the fuckers in. Shocker!\n• This quest costs approximately ₽240,000",
Tasks.tasks.Blood3: "• Find and Mark all 3 Fuel Stashes on Woods with MS2000 Markets\n• Survive and Extract\n• Boy, you use a *lot* of those markers, huh?",
Tasks.tasks.Sew2: "• Find 2 Gzhels in any condition\n• They cost like 200k a pop, you can't miss 'em\n• Hand the body armor over to Ragman",
Tasks.tasks.KeytoSuccess: "• Find both parts of the Clothes Design Handbook on Interchange\n• Hand the literature over to Ragman",
Tasks.tasks.NoFuss: "• Reach Loyalty III with Therapist",
Tasks.tasks.Supervisor: "• Obtain the Goshan cash register key\n• Hand the key over to Ragman",
Tasks.tasks.Sew3: "• Find 2 6B13 assault armors in raid\n• Hand the body armor over to Ragman",
Tasks.tasks.LHinaC1: "• Find 2 Bronze Lions in raid\n• Find 2 Horse Figurines in raid\n• Find 2 Cat Figurines in raid\n• Find 1 Roler in raid\n• Find 1 Golden Egg in rain\n• Hand these illustrious items over to Ragman ",
Tasks.tasks.LHinaC2: "• Find 3 Antique Teapots in raid\n• Find 2 Antique Vases in raid\n• Find an Axel Figurine in raid\n• Find 2 Raven Figurines in raid\n• Hand these even more illustrious items over to Ragman ",
Tasks.tasks.Sew4: "• Find 2 TV-109+TV-106 Rigs in raid\n• Find 2 Blackrock rigs in raid\n• Hand the rigs over to Ragman\n",
Tasks.tasks.Charisma: "• Reach Charisma Level 10",
Tasks.tasks.Acquaintance: "• Find 3 Iskras in raid\n• Find 2 Packs of Instant Noodles in raid\n• Find 2 Cans of Beef Stew in raid\n• Deliver unto Jaeger his meals most delectable",
Tasks.tasks.Unprotected: "• Eliminate 5 Scavs while not wearing body armor on Woods",
Tasks.tasks.Thrifty: "• Stash an Iskra and Water Bottle in ZB-014\n• Stash an Iskra and Water Bottle in ZB-016",
Tasks.tasks.Zhivchik: "• Survive 5 minutes of dehydration on any map other than Factory\n• Survive and Extract",
Tasks.tasks.Wounded: "• Eliminate 3 Scavs while suffering from the Pain effect\n• Neat Fact: There are 2 different Pain effects; the status effect and what happens when you get hit! Both effects count for this quest.",
Tasks.tasks.ToughGuy: "• Eliminate 3 Scavs on Woods in a single raid without using any medicine",
Tasks.tasks.CourtesyVisit: "• Find the Chairman's house on Shoreline\n• Find the Fisherman's house on Shoreline\n• Find the Priest's house on Shoreline\n• Survive and Extract",
Tasks.tasks.Nostalgia: "• Find Jaeger's Photo Album in the Resort on Shoreline\n• Hand the album over to Jaeger",
Tasks.tasks.Junkie: "• Eliminate 15 Scavs on Woods while under any stimulant effect",
Tasks.tasks.Eagle: "• Eliminate 6 Scavs between 21:00 and 04:00 without using any NVGs or thermals (except Factory)",
Tasks.tasks.Medic: "• Reach Vitality Level 5",
Tasks.tasks.Ambulance: "• Find a Portable Defibrillator in raid\n• Fins 2 CMS Kits\n• Hand the medical equipment over to Jaeger",
Tasks.tasks.SecurePerimeter: "• Eliminate 6 PMCs in the Office area on Factory",
Tasks.tasks.Reserve: "• Find the Food Storage location on Reserve\n• Survive and Extract",
Tasks.tasks.ForestCleaning: "• Eliminate 30 Scavs",
Tasks.tasks.Controller: "• Eliminate 2 PMCs while they are stunned",
Tasks.tasks.EvilWatchman: "• Eliminate 5 PMCs in Dorms on Customs",
Tasks.tasks.FishingPlace: "• Find 2 Labs Access Cards in raid\n• Hand the cards over to Jaeger",
Tasks.tasks.Trophy: "• Eliminate Reshala\n• Find the Golden TT in raid\n• Hand the pistol over to Jaeger",
Tasks.tasks.Justice: "• Eliminate 3 of Reshala's Guards",
Tasks.tasks.Sellout: "• Eliminate Killa\n• Find Killa's Helmet in Raid\n• Hand the helmet over to Jaeger",
Tasks.tasks.WoodsKeeper: "• Eliminate Shturman\n• Find 1 Stash Key in raid\n• Hand the key over to Jaeger",
Tasks.tasks.HuntingTrip: "• Eliminate Shturman with a headshot from 75+ meters while using an M700 with the TAC30",
Tasks.tasks.FactoryChief: "• Eliminate Tagilla\n• Find 1 Boss Cap in raid\n• Hand the hat over to Jaeger",
Tasks.tasks.Eraser1: "• Eliminate Glukhar",
Tasks.tasks.Eraser2: "• Eliminate 6 Raiders",
Tasks.tasks.TarkShoot1: "• Eliminate 5 Scavs while using a bolt-action rifle with iron sights from over 40 meters away",
Tasks.tasks.TarkShoot2: "• Hit 3 leg shots while using a bolt-action rifle with iron sights from over 40 meters away\n• Hit 3 headshots while using a bolt-action rifle with iron sights from over 40 meters away",
Tasks.tasks.TarkShoot3: "• Eliminate 3 PMCs with bolt-action rifles from less than 25 meters\n• Better hit Factory!",
Tasks.tasks.TarkShoot4: "• Eliminate 5 PMCs with bolt-action rifles from over 80 meters away",
Tasks.tasks.TarkShoot5: "• Eliminate 8 Scavs on Customs with bolt-action rifles between 21:00 and 05:00",
Tasks.tasks.TarkShoot6: "• Eliminate 5 Sniper Scavs with bolt-action rifles",
Tasks.tasks.TarkShoot7: "• Eliminate 5 PMCs with suppressed bolt-action rifles from at least 45 meters",
Tasks.tasks.TarkShoot8: "• Do not die\n• Eliminate 3 PMCs with headshots while using a bolt-action rifle.",
Tasks.tasks.FlashDrives2: "• Find 3 Flash Drives in raid\n• Hand the flash drives over to Jaeger",
Tasks.tasks.Sadist: "• Eliminate Sanitar\nCOMPLETING THIS QUEST LOCKS OFF \"Colleagues\"",
Tasks.tasks.PestControl: "• Eliminate 10 Scavs in the Barracks of Reserve",
Tasks.tasks.Hermit: "• Obtain the message from Jaeger's friend on Lighthouse\n• Hand the message over to Jaeger",
Tasks.tasks.Outcasts: "• Eliminate 10 Rogues\n• Rogues generally spawn on Lighthouse, in case you were unaware.",
Tasks.tasks.StrayDogs: "• Eliminate the Gooners\n• Find their Goon Cave",
Tasks.tasks.Sausage: "• Find a Salty Dog Sausage in raid\n• Hand the Sausage over to Jaeger\n• Scout the Shestyorochka store at Nikitskaya street\n• Scout the Sparja store at Primorsky ave\n• Scout the Sparja store in Pinewood hotel\n• Scout the Goshan store in Concordia",
Tasks.tasks.OldFiresteel: "• \n",
Tasks.tasks.AntiqueAxe: "• \n",
Tasks.tasks.AntiqueBook: "• \n",
Tasks.tasks.FireKlean: "• \n",
Tasks.tasks.GoldenCock: "• \n",
Tasks.tasks.Yeehaw: "• \n",
Tasks.tasks.BeardOil: "• \n",
Tasks.tasks.GPhone: "• \n",
Tasks.tasks.DevilDog: "• \n",
Tasks.tasks.Sprats: "• \n",
Tasks.tasks.Mustache: "• \n",
Tasks.tasks.Kotton: "• \n",
Tasks.tasks.LupoBeans: "• \n",
Tasks.tasks.Pestily: "• \n",
Tasks.tasks.Raven: "• \n",
Tasks.tasks.Shroud: "• \n",
Tasks.tasks.Veritas: "• \n",
Tasks.tasks.Tea: "• \n",
Tasks.tasks.Smoke: "• \n",
Tasks.tasks.Armband: "• \n",
Tasks.tasks.RatCola: "• \n",
Tasks.tasks.LootLord: "• \n",
Tasks.tasks.WZWallet: "• \n",
Tasks.tasks.RatPoison: "• \n",
Tasks.tasks.Missam: "• \n",
Tasks.tasks.Cassette: "• \n",
Tasks.tasks.BakeEzy: "• \n",
Tasks.tasks.JohnB: "• \n",
Tasks.tasks.GloriousE: "• \n",
Tasks.tasks.RedBeard: "• \n",
Tasks.tasks.RedPACA: "• \n",
Tasks.tasks.Gingy: "• \n",
Tasks.tasks.Egg: "• \n",
Tasks.tasks.PressPass: "• \n",
Tasks.tasks.Axel: "• \n",
Tasks.tasks.BEARBuddy: "• \n",
}
const Previous:= {
Tasks.tasks.Debut : "Shooting Cans",
Tasks.tasks.Search : "Debut",
Tasks.tasks.Checking : "Luxurious Life",
Tasks.tasks.Shootout : "Background Check",
Tasks.tasks.PastDelivery : "Background Check",
Tasks.tasks.BPDepot : "Delivery from the Past",
Tasks.tasks.Bunker1 : "BP Depot",
Tasks.tasks.Bunker2 : "The Bunker - Part 1",
Tasks.tasks.BadRep : "BP Depot",
Tasks.tasks.IceCream : "Bad Rep Evidence",
Tasks.tasks.Renegades : "The Bunker - Part 2",
Tasks.tasks.Documents : "No Place for Renegades",
Tasks.tasks.Postman1 : "Ice Cream Cones",
Tasks.tasks.ShakingupTeller : "Ice Cream Cones",
Tasks.tasks.Punisher1 : "Shaking up the Teller",
Tasks.tasks.Punisher2 : "The Punisher - Part 1",
Tasks.tasks.Punisher3 : "The Punisher - Part 2",
Tasks.tasks.Punisher4 : "The Punisher - Part 3",
Tasks.tasks.Punisher5 : "The Punisher - Part 4",
Tasks.tasks.Punisher6 : "The Punisher - Part 5",
Tasks.tasks.Anesthesia : "Shaking up the Teller",
Tasks.tasks.Grenadier : "-",
Tasks.tasks.TestDrive1 : "Grenadier",
Tasks.tasks.Mediator : "Shaking up the Teller",
Tasks.tasks.PolikhimHobo : "Chemical - Part 1",
Tasks.tasks.Regulated : "Polikhim Hobo",
Tasks.tasks.BigCustomer : "Chemical - Part 3",
Tasks.tasks.Intimidator : "The Punisher - Part 6",
Tasks.tasks.EasyJob1 : "The Punisher - Part 2",
Tasks.tasks.EasyJob2 : "Easy Job - Part 1",
Tasks.tasks.Recon : "Easy Job - Part 1",
Tasks.tasks.Shortage : "First In Line",
Tasks.tasks.Aq1 : "Shortage",
Tasks.tasks.Aq2 : "Operation Aquarius - Part 1",
Tasks.tasks.Gasan1 : "Shortage",
Tasks.tasks.Gasan2 : "Sanitary Standards - Part 1",
Tasks.tasks.Painkill : "Sanitary Standards - Part 2",
Tasks.tasks.Pharm : "Painkiller",
Tasks.tasks.DHistory : "Pharmacist",
Tasks.tasks.Car : "Pharmacist",
Tasks.tasks.Supply : "Pharmacist",
Tasks.tasks.HCP1 : "Pharmacist",
Tasks.tasks.HCP2 : "Health Care Privacy - Part 1",
Tasks.tasks.HCP3 : "Health Care Privacy - Part 2",
Tasks.tasks.HCP4 : "Health Care Privacy - Part 3",
Tasks.tasks.Athlete : "Health Care Privacy - Part 4",
Tasks.tasks.PClinic : "Health Care Privacy - Part 4",
Tasks.tasks.HCP5 : "Health Care Privacy - Part 4",
Tasks.tasks.Decontam : "Health Care Privacy - Part 5\nPrivate Clinic",
Tasks.tasks.Wares : "Pharmacist",
Tasks.tasks.Coll1 : "General Wares",
Tasks.tasks.Coll2 : "Colleagues - Part 1",
Tasks.tasks.Coll3 : "Colleagues - Part 2\nRigged Game\nChemistry Closet",
Tasks.tasks.Postman2 : "Postman Pat - Part 1",
Tasks.tasks.Curiosity : "Chemical - Part 3",
Tasks.tasks.Crisis : "-",
Tasks.tasks.Seaside : "Disease History",
Tasks.tasks.LostContact : "Health Care Privacy - Part 2",
Tasks.tasks.Trafficking : "Lost Contact",
Tasks.tasks.Supplier : "Supplier",
Tasks.tasks.Extortion : "Extortion",
Tasks.tasks.Stirrup : "Stirrup",
Tasks.tasks.FlashDrives1 : "What's on the Flash Drive?",
Tasks.tasks.GoldenSwag : "Golden Swag",
Tasks.tasks.Chem1 : "Chemical",
Tasks.tasks.Chem2 : "Chemical",
Tasks.tasks.Chem3 : "Chemical",
Tasks.tasks.Chem4 : "Chemical",
Tasks.tasks.Vit1 : "Vitamins",
Tasks.tasks.Vit2 : "Vitamins",
Tasks.tasks.FFtW1 : "Friend from the West",
Tasks.tasks.FFtW2 : "Friend from the West",
Tasks.tasks.LL1 : "Lend-Lease",
Tasks.tasks.Setup : "Setup",
Tasks.tasks.Informed : "Informed Means Armed",
Tasks.tasks.Chumming : "Chumming",
Tasks.tasks.Bullshit : "Bullshit",
Tasks.tasks.Flint : "Flint",
Tasks.tasks.KindaSabotage : "Kind of Sabotage",
Tasks.tasks.RiggedGame : "Rigged Game",
Tasks.tasks.SafeCorridor : "Safe Corridor",
Tasks.tasks.LongRoad : "Long Road",
Tasks.tasks.MissingCargo : "Missing Cargo",
Tasks.tasks.Fishing : "Fishing Gear",
Tasks.tasks.TigrSafari : "Tigr Safari",
Tasks.tasks.ScrapMetal : "Scrap Metal",
Tasks.tasks.EagleEye : "Eagle Eye",
Tasks.tasks.Blueberry1 : "Humanitarian Supplies",
Tasks.tasks.Cult1 : "The Cult",
Tasks.tasks.Cult2 : "The Cult",
Tasks.tasks.SpaTour1 : "Spa Tour",
Tasks.tasks.SpaTour2 : "Spa Tour",
Tasks.tasks.SpaTour3 : "Spa Tour",
Tasks.tasks.SpaTour4 : "Spa Tour",
Tasks.tasks.SpaTour5 : "Spa Tour",
Tasks.tasks.SpaTour6 : "Spa Tour",
Tasks.tasks.SpaTour7 : "Spa Tour",
Tasks.tasks.Cargo1 : "Cargo X",
Tasks.tasks.Cargo2 : "Cargo X",
Tasks.tasks.Cargo3 : "Cargo X",
Tasks.tasks.WetJob1 : "Wet Job",
Tasks.tasks.WetJob2 : "Wet Job",
Tasks.tasks.WetJob3 : "Wet Job",
Tasks.tasks.WetJob4 : "Wet Job",
Tasks.tasks.WetJob5 : "Wet Job",
Tasks.tasks.WetJob6 : "Wet Job",
Tasks.tasks.TheGuide : "The Guide",
Tasks.tasks.Samples : "Samples",
Tasks.tasks.Terragroup : "Terragroup Employee",
Tasks.tasks.LL2 : "Lend-Lease",
Tasks.tasks.Blueberry2 : "Peacekeeping Mission",
Tasks.tasks.ClassTech : "Classified Technologies",
Tasks.tasks.RevisReserve : "Revision",
Tasks.tasks.Cargo4 : "Cargo X",
Tasks.tasks.Insomnia : "Insomnia",
Tasks.tasks.Overpopulation : "Overpopulation",
Tasks.tasks.RevisLighthouse : "Revision",
Tasks.tasks.Intro : "Introduction",
Tasks.tasks.GS1 : "Gunsmith",
Tasks.tasks.GS2 : "Gunsmith",
Tasks.tasks.GS3 : "Gunsmith",
Tasks.tasks.GS4 : "Gunsmith",
Tasks.tasks.GS5 : "Gunsmith",
Tasks.tasks.GS6 : "Gunsmith",
Tasks.tasks.GS7 : "Gunsmith",
Tasks.tasks.GS8 : "Gunsmith",
Tasks.tasks.GS9 : "Gunsmith",
Tasks.tasks.GS10 : "Gunsmith",
Tasks.tasks.GS11 : "Gunsmith",
Tasks.tasks.GS12 : "Gunsmith",
Tasks.tasks.GS13 : "Gunsmith",
Tasks.tasks.GS14 : "Gunsmith",
Tasks.tasks.GS15 : "Gunsmith",
Tasks.tasks.GS16 : "Gunsmith",
Tasks.tasks.GS17 : "Gunsmith",
Tasks.tasks.GS18 : "Gunsmith",
Tasks.tasks.GS19 : "Gunsmith",
Tasks.tasks.GS20 : "Gunsmith",
Tasks.tasks.GS21 : "Gunsmith",
Tasks.tasks.GS22 : "Gunsmith",
Tasks.tasks.Signal1 : "Signal",
Tasks.tasks.Insider : "Insider",
Tasks.tasks.Signal2 : "Signal",
Tasks.tasks.Scout : "Scout",
Tasks.tasks.SurpGoods : "Surplus Goods",
Tasks.tasks.BackDoor : "Back Door",
Tasks.tasks.Signal3 : "Signal",
Tasks.tasks.Signal4 : "Signal",
Tasks.tasks.Farming1 : "Farming",
Tasks.tasks.Farming2 : "Farming",
Tasks.tasks.BadHabit : "Bad Habit",
Tasks.tasks.Farming3 : "Farming",
Tasks.tasks.Farming4 : "Farming",
Tasks.tasks.PsychoSniper : "Psycho Sniper",
Tasks.tasks.ShooterBorn : "A Shooter Born In Heaven",
Tasks.tasks.Fertilizers : "Fertilizers",
Tasks.tasks.Import : "Import",
Tasks.tasks.ChemCloset : "Chemical Closet",
Tasks.tasks.CorpoSecret : "Corporate Secrets",
Tasks.tasks.EnergyCrisis : "Energy Crisis",
Tasks.tasks.Broadcast1 : "Broadcast",
Tasks.tasks.OnlyBusiness : "Only Business",
Tasks.tasks.MUGA : "Make ULTRA Great Again",
Tasks.tasks.BigSale : "Big Sale",
Tasks.tasks.FuelMatter : "A Fuel Matter",
Tasks.tasks.Inventory : "Inventory Check",
Tasks.tasks.Blood1 : "The Blood of War",
Tasks.tasks.DressedtoKill : "Dressed to Kill",
Tasks.tasks.Gratitude : "Gratitude",
Tasks.tasks.Delivery : "Hot Delivery",
Tasks.tasks.Scav : "Scavenger",
Tasks.tasks.SalesNight : "Sales Night",
Tasks.tasks.Data1 : "Database",
Tasks.tasks.Data2 : "Database",
Tasks.tasks.Minibus : "Minibus",
Tasks.tasks.Sew1 : "Sew it Good",
Tasks.tasks.Blood2 : "The Blood of War",
Tasks.tasks.Blood3 : "The Blood of War",
Tasks.tasks.Sew2 : "Sew it Good",
Tasks.tasks.KeytoSuccess : "The Key to Success",
Tasks.tasks.NoFuss : "No Fuss Needed",
Tasks.tasks.Supervisor : "Supervisor",
Tasks.tasks.Sew3 : "Sew it Good",
Tasks.tasks.LHinaC1 : "Living High is Not a Crime",
Tasks.tasks.LHinaC2 : "Living High is Not a Crime",
Tasks.tasks.Sew4 : "Sew it Good",
Tasks.tasks.Charisma : "Charisma Brings Success",
Tasks.tasks.Acquaintance : "Acquaintance",
Tasks.tasks.Unprotected : "The Survivalist Path",
Tasks.tasks.Thrifty : "The Survivalist Path",
Tasks.tasks.Zhivchik : "The Survivalist Path",
Tasks.tasks.Wounded : "The Survivalist Path",
Tasks.tasks.ToughGuy : "The Survivalist Path",
Tasks.tasks.CourtesyVisit : "Courtesy Visit",
Tasks.tasks.Nostalgia : "Nostalgia",
Tasks.tasks.Junkie : "The Survivalist Path",
Tasks.tasks.Eagle : "The Survivalist Path",
Tasks.tasks.Medic : "The Survivalist Path",
Tasks.tasks.Ambulance : "Ambulance",
Tasks.tasks.SecurePerimeter : "The Huntsman Path",
Tasks.tasks.Reserve : "Reserve",
Tasks.tasks.ForestCleaning : "The Huntsman Path",
Tasks.tasks.Controller : "The Huntsman Path",
Tasks.tasks.EvilWatchman : "The Huntsman Path",
Tasks.tasks.FishingPlace : "Fishing Place",
Tasks.tasks.Trophy : "The Huntsman Path",
Tasks.tasks.Justice : "The Huntsman Path",
Tasks.tasks.Sellout : "The Huntsman Path",
Tasks.tasks.WoodsKeeper : "The Huntsman Path",
Tasks.tasks.HuntingTrip : "Hunting Trip",
Tasks.tasks.FactoryChief : "The Huntsman Path",
Tasks.tasks.Eraser1 : "The Huntsman Path",
Tasks.tasks.Eraser2 : "The Huntsman Path",
Tasks.tasks.TarkShoot1 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot2 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot3 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot4 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot5 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot6 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot7 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot8 : "The Tarkov Shooter",
Tasks.tasks.FlashDrives2 : "Shady Business",
Tasks.tasks.Sadist : "The Huntsman Path",
Tasks.tasks.PestControl : "Pest Control",
Tasks.tasks.Hermit : "Hermit",
Tasks.tasks.Outcasts : "The Huntsman Path",
Tasks.tasks.StrayDogs : "Stray Dogs",
Tasks.tasks.Sausage : "The Delicious Sausage",
Tasks.tasks.OldFiresteel: "",
Tasks.tasks.AntiqueAxe: "",
Tasks.tasks.AntiqueBook: "",
Tasks.tasks.FireKlean: "",
Tasks.tasks.GoldenCock: "",
Tasks.tasks.Yeehaw: "",
Tasks.tasks.BeardOil: "",
Tasks.tasks.GPhone: "",
Tasks.tasks.DevilDog: "",
Tasks.tasks.Sprats: "",
Tasks.tasks.Mustache: "",
Tasks.tasks.Kotton: "",
Tasks.tasks.LupoBeans: "",
Tasks.tasks.Pestily: "",
Tasks.tasks.Raven: "",
Tasks.tasks.Shroud: "",
Tasks.tasks.Veritas: "",
Tasks.tasks.Tea: "",
Tasks.tasks.Smoke: "",
Tasks.tasks.Armband: "",
Tasks.tasks.RatCola: "",
Tasks.tasks.LootLord: "",
Tasks.tasks.WZWallet: "",
Tasks.tasks.RatPoison: "",
Tasks.tasks.Missam: "",
Tasks.tasks.Cassette: "",
Tasks.tasks.BakeEzy: "",
Tasks.tasks.JohnB: "",
Tasks.tasks.GloriousE: "",
Tasks.tasks.RedBeard: "",
Tasks.tasks.RedPACA: "",
Tasks.tasks.Gingy: "",
Tasks.tasks.Egg: "",
Tasks.tasks.PressPass: "",
Tasks.tasks.Axel: "",
Tasks.tasks.BEARBuddy: "",
}
const LeadsTo:= {
Tasks.tasks.Debut : "Search Mission\nLuxurious Life",
Tasks.tasks.Search : "-",
Tasks.tasks.Checking : "Shootout Picnic\nDelivery from the Past",
Tasks.tasks.Shootout : "-",
Tasks.tasks.PastDelivery : "BP Depot",
Tasks.tasks.BPDepot : "Bad Rep Evidence\nThe Bunker - Part 1",
Tasks.tasks.Bunker1 : "The Bunker - Part 2",
Tasks.tasks.Bunker2 : "No Place for Renegades",
Tasks.tasks.BadRep : "Bad Rep Evidence",
Tasks.tasks.IceCream : "Ice Cream Cones",
Tasks.tasks.Renegades : "Documents",
Tasks.tasks.Documents : "-",
Tasks.tasks.Postman1 : "Postman Pat - Part 2",
Tasks.tasks.ShakingupTeller : "The Punisher - Part 1",
Tasks.tasks.Punisher1 : "The Punisher - Part 2",
Tasks.tasks.Punisher2 : "The Punisher - Part 3\nEasy Job - Part 1",
Tasks.tasks.Punisher3 : "The Punisher - Part 4",
Tasks.tasks.Punisher4 : "The Punisher - Part 5",
Tasks.tasks.Punisher5 : "The Punisher - Part 6",
Tasks.tasks.Punisher6 : "Intimidator",
Tasks.tasks.Anesthesia : "Rigged Game\nSamples\nChemistry Closet",
Tasks.tasks.Grenadier : "Test Drive - Part 1",
Tasks.tasks.TestDrive1 : "-",
Tasks.tasks.Mediator : "-",
Tasks.tasks.PolikhimHobo : "-",
Tasks.tasks.Regulated : "-",
Tasks.tasks.BigCustomer : "Safe Corridor",
Tasks.tasks.Intimidator : "-",
Tasks.tasks.EasyJob1 : "Easy Job - Part 2",
Tasks.tasks.EasyJob2 : "-",
Tasks.tasks.Recon : "-",
Tasks.tasks.Shortage : "Operation Aquarius - Part 1\nSanitary Standards - Part 1",
Tasks.tasks.Aq1 : "Operation Aquarius - Part 2",
Tasks.tasks.Aq2 : "-",
Tasks.tasks.Gasan1 : "Sanitary Standards - Part 2",
Tasks.tasks.Gasan2 : "Painkiller",
Tasks.tasks.Painkill : "Pharmacist",
Tasks.tasks.Pharm : "General Wares\nHealth Care Privacy - Part 1\nCar Repair\nDisease History\nSupply Plans or\nKind of Sabotage",
Tasks.tasks.DHistory : "Seaside Vacation",
Tasks.tasks.Car : "-",
Tasks.tasks.Supply : "The Huntsman Path - Woods Keeper",
Tasks.tasks.HCP1 : "Health Care Privacy - Part 2",
Tasks.tasks.HCP2 : "Health Care Privacy - Part 3\nLost Contact",
Tasks.tasks.HCP3 : "Health Care Privacy - Part 4",
Tasks.tasks.HCP4 : "Health Care Privacy - Part 5\nPrivate Clinic\nAthlete",
Tasks.tasks.Athlete : "Athlete",
Tasks.tasks.PClinic : "Decontamination Service",
Tasks.tasks.HCP5 : "Decontamination Service",
Tasks.tasks.Decontam : "-",
Tasks.tasks.Wares : "Colleagues - Part 1",
Tasks.tasks.Coll1 : "Colleagues - Part 2\nChemistry Closet",
Tasks.tasks.Coll2 : "Colleagues - Part 3 or\nThe Huntsman Path - Sadist",
Tasks.tasks.Coll3 : "Colleagues",
Tasks.tasks.Postman2 : "-",
Tasks.tasks.Curiosity : "Safe Corridor",
Tasks.tasks.Crisis : "-",
Tasks.tasks.Seaside : "-",
Tasks.tasks.LostContact : "Drug Trafficking",
Tasks.tasks.Trafficking : "-",
Tasks.tasks.Supplier : "Supplier",
Tasks.tasks.Extortion : "Extortion",
Tasks.tasks.Stirrup : "Stirrup",
Tasks.tasks.FlashDrives1 : "What's on the Flash Drive?",
Tasks.tasks.GoldenSwag : "Golden Swag",
Tasks.tasks.Chem1 : "Chemical",
Tasks.tasks.Chem2 : "Chemical",
Tasks.tasks.Chem3 : "Chemical",
Tasks.tasks.Chem4 : "Chemical",
Tasks.tasks.Vit1 : "Vitamins",
Tasks.tasks.Vit2 : "Vitamins",
Tasks.tasks.FFtW1 : "Friend from the West",
Tasks.tasks.FFtW2 : "Friend from the West",
Tasks.tasks.LL1 : "Lend-Lease",
Tasks.tasks.Setup : "Setup",
Tasks.tasks.Informed : "Informed Means Armed",
Tasks.tasks.Chumming : "Chumming",
Tasks.tasks.Bullshit : "Bullshit",
Tasks.tasks.Flint : "Flint",
Tasks.tasks.KindaSabotage : "Kind of Sabotage",
Tasks.tasks.RiggedGame : "Rigged Game",
Tasks.tasks.SafeCorridor : "Safe Corridor",
Tasks.tasks.LongRoad : "Long Road",
Tasks.tasks.MissingCargo : "Missing Cargo",
Tasks.tasks.Fishing : "Fishing Gear",
Tasks.tasks.TigrSafari : "Tigr Safari",
Tasks.tasks.ScrapMetal : "Scrap Metal",
Tasks.tasks.EagleEye : "Eagle Eye",
Tasks.tasks.Blueberry1 : "Humanitarian Supplies",
Tasks.tasks.Cult1 : "The Cult",
Tasks.tasks.Cult2 : "The Cult",
Tasks.tasks.SpaTour1 : "Spa Tour",
Tasks.tasks.SpaTour2 : "Spa Tour",
Tasks.tasks.SpaTour3 : "Spa Tour",
Tasks.tasks.SpaTour4 : "Spa Tour",
Tasks.tasks.SpaTour5 : "Spa Tour",
Tasks.tasks.SpaTour6 : "Spa Tour",
Tasks.tasks.SpaTour7 : "Spa Tour",
Tasks.tasks.Cargo1 : "Cargo X",
Tasks.tasks.Cargo2 : "Cargo X",
Tasks.tasks.Cargo3 : "Cargo X",
Tasks.tasks.WetJob1 : "Wet Job",
Tasks.tasks.WetJob2 : "Wet Job",
Tasks.tasks.WetJob3 : "Wet Job",
Tasks.tasks.WetJob4 : "Wet Job",
Tasks.tasks.WetJob5 : "Wet Job",
Tasks.tasks.WetJob6 : "Wet Job",
Tasks.tasks.TheGuide : "The Guide",
Tasks.tasks.Samples : "Samples",
Tasks.tasks.Terragroup : "Terragroup Employee",
Tasks.tasks.LL2 : "Lend-Lease",
Tasks.tasks.Blueberry2 : "Peacekeeping Mission",
Tasks.tasks.ClassTech : "Classified Technologies",
Tasks.tasks.RevisReserve : "Revision",
Tasks.tasks.Cargo4 : "Cargo X",
Tasks.tasks.Insomnia : "Insomnia",
Tasks.tasks.Overpopulation : "Overpopulation",
Tasks.tasks.RevisLighthouse : "Revision",
Tasks.tasks.Intro : "Introduction",
Tasks.tasks.GS1 : "Gunsmith",
Tasks.tasks.GS2 : "Gunsmith",
Tasks.tasks.GS3 : "Gunsmith",
Tasks.tasks.GS4 : "Gunsmith",
Tasks.tasks.GS5 : "Gunsmith",
Tasks.tasks.GS6 : "Gunsmith",
Tasks.tasks.GS7 : "Gunsmith",
Tasks.tasks.GS8 : "Gunsmith",
Tasks.tasks.GS9 : "Gunsmith",
Tasks.tasks.GS10 : "Gunsmith",
Tasks.tasks.GS11 : "Gunsmith",
Tasks.tasks.GS12 : "Gunsmith",
Tasks.tasks.GS13 : "Gunsmith",
Tasks.tasks.GS14 : "Gunsmith",
Tasks.tasks.GS15 : "Gunsmith",
Tasks.tasks.GS16 : "Gunsmith",
Tasks.tasks.GS17 : "Gunsmith",
Tasks.tasks.GS18 : "Gunsmith",
Tasks.tasks.GS19 : "Gunsmith",
Tasks.tasks.GS20 : "Gunsmith",
Tasks.tasks.GS21 : "Gunsmith",
Tasks.tasks.GS22 : "Gunsmith",
Tasks.tasks.Signal1 : "Signal",
Tasks.tasks.Insider : "Insider",
Tasks.tasks.Signal2 : "Signal",
Tasks.tasks.Scout : "Scout",
Tasks.tasks.SurpGoods : "Surplus Goods",
Tasks.tasks.BackDoor : "Back Door",
Tasks.tasks.Signal3 : "Signal",
Tasks.tasks.Signal4 : "Signal",
Tasks.tasks.Farming1 : "Farming",
Tasks.tasks.Farming2 : "Farming",
Tasks.tasks.BadHabit : "Bad Habit",
Tasks.tasks.Farming3 : "Farming",
Tasks.tasks.Farming4 : "Farming",
Tasks.tasks.PsychoSniper : "Psycho Sniper",
Tasks.tasks.ShooterBorn : "A Shooter Born In Heaven",
Tasks.tasks.Fertilizers : "Fertilizers",
Tasks.tasks.Import : "Import",
Tasks.tasks.ChemCloset : "Chemical Closet",
Tasks.tasks.CorpoSecret : "Corporate Secrets",
Tasks.tasks.EnergyCrisis : "Energy Crisis",
Tasks.tasks.Broadcast1 : "Broadcast",
Tasks.tasks.OnlyBusiness : "Only Business",
Tasks.tasks.MUGA : "Make ULTRA Great Again",
Tasks.tasks.BigSale : "Big Sale",
Tasks.tasks.FuelMatter : "A Fuel Matter",
Tasks.tasks.Inventory : "Inventory Check",
Tasks.tasks.Blood1 : "The Blood of War",
Tasks.tasks.DressedtoKill : "Dressed to Kill",
Tasks.tasks.Gratitude : "Gratitude",
Tasks.tasks.Delivery : "Hot Delivery",
Tasks.tasks.Scav : "Scavenger",
Tasks.tasks.SalesNight : "Sales Night",
Tasks.tasks.Data1 : "Database",
Tasks.tasks.Data2 : "Database",
Tasks.tasks.Minibus : "Minibus",
Tasks.tasks.Sew1 : "Sew it Good",
Tasks.tasks.Blood2 : "The Blood of War",
Tasks.tasks.Blood3 : "The Blood of War",
Tasks.tasks.Sew2 : "Sew it Good",
Tasks.tasks.KeytoSuccess : "The Key to Success",
Tasks.tasks.NoFuss : "No Fuss Needed",
Tasks.tasks.Supervisor : "Supervisor",
Tasks.tasks.Sew3 : "Sew it Good",
Tasks.tasks.LHinaC1 : "Living High is Not a Crime",
Tasks.tasks.LHinaC2 : "Living High is Not a Crime",
Tasks.tasks.Sew4 : "Sew it Good",
Tasks.tasks.Charisma : "Charisma Brings Success",
Tasks.tasks.Acquaintance : "Acquaintance",
Tasks.tasks.Unprotected : "The Survivalist Path",
Tasks.tasks.Thrifty : "The Survivalist Path",
Tasks.tasks.Zhivchik : "The Survivalist Path",
Tasks.tasks.Wounded : "The Survivalist Path",
Tasks.tasks.ToughGuy : "The Survivalist Path",
Tasks.tasks.CourtesyVisit : "Courtesy Visit",
Tasks.tasks.Nostalgia : "Nostalgia",
Tasks.tasks.Junkie : "The Survivalist Path",
Tasks.tasks.Eagle : "The Survivalist Path",
Tasks.tasks.Medic : "The Survivalist Path",
Tasks.tasks.Ambulance : "Ambulance",
Tasks.tasks.SecurePerimeter : "The Huntsman Path",
Tasks.tasks.Reserve : "Reserve",
Tasks.tasks.ForestCleaning : "The Huntsman Path",
Tasks.tasks.Controller : "The Huntsman Path",
Tasks.tasks.EvilWatchman : "The Huntsman Path",
Tasks.tasks.FishingPlace : "Fishing Place",
Tasks.tasks.Trophy : "The Huntsman Path",
Tasks.tasks.Justice : "The Huntsman Path",
Tasks.tasks.Sellout : "The Huntsman Path",
Tasks.tasks.WoodsKeeper : "The Huntsman Path",
Tasks.tasks.HuntingTrip : "Hunting Trip",
Tasks.tasks.FactoryChief : "The Huntsman Path",
Tasks.tasks.Eraser1 : "The Huntsman Path",
Tasks.tasks.Eraser2 : "The Huntsman Path",
Tasks.tasks.TarkShoot1 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot2 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot3 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot4 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot5 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot6 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot7 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot8 : "The Tarkov Shooter",
Tasks.tasks.FlashDrives2 : "Shady Business",
Tasks.tasks.Sadist : "The Huntsman Path",
Tasks.tasks.PestControl : "Pest Control",
Tasks.tasks.Hermit : "Hermit",
Tasks.tasks.Outcasts : "The Huntsman Path",
Tasks.tasks.StrayDogs : "Stray Dogs",
Tasks.tasks.Sausage : "The Delicious Sausage",
Tasks.tasks.OldFiresteel: "",
Tasks.tasks.AntiqueAxe: "",
Tasks.tasks.AntiqueBook: "",
Tasks.tasks.FireKlean: "",
Tasks.tasks.GoldenCock: "",
Tasks.tasks.Yeehaw: "",
Tasks.tasks.BeardOil: "",
Tasks.tasks.GPhone: "",
Tasks.tasks.DevilDog: "",
Tasks.tasks.Sprats: "",
Tasks.tasks.Mustache: "",
Tasks.tasks.Kotton: "",
Tasks.tasks.LupoBeans: "",
Tasks.tasks.Pestily: "",
Tasks.tasks.Raven: "",
Tasks.tasks.Shroud: "",
Tasks.tasks.Veritas: "",
Tasks.tasks.Tea: "",
Tasks.tasks.Smoke: "",
Tasks.tasks.Armband: "",
Tasks.tasks.RatCola: "",
Tasks.tasks.LootLord: "",
Tasks.tasks.WZWallet: "",
Tasks.tasks.RatPoison: "",
Tasks.tasks.Missam: "",
Tasks.tasks.Cassette: "",
Tasks.tasks.BakeEzy: "",
Tasks.tasks.JohnB: "",
Tasks.tasks.GloriousE: "",
Tasks.tasks.RedBeard: "",
Tasks.tasks.RedPACA: "",
Tasks.tasks.Gingy: "",
Tasks.tasks.Egg: "",
Tasks.tasks.PressPass: "",
Tasks.tasks.Axel: "",
Tasks.tasks.BEARBuddy: "",
}
const WikiLinks:= {
Tasks.tasks.Debut : "Debut",
Tasks.tasks.Search : "Search Mission",
Tasks.tasks.Checking : "Background Check",
Tasks.tasks.Shootout : "Shootout Picnic",
Tasks.tasks.PastDelivery : "Delivery from the Past",
Tasks.tasks.BPDepot : "BP Depot",
Tasks.tasks.Bunker1 : "The Bunker",
Tasks.tasks.Bunker2 : "The Bunker",
Tasks.tasks.BadRep : "Bad Rep Evidence",
Tasks.tasks.IceCream : "Ice Cream Cones",
Tasks.tasks.Renegades : "No Place for Renegades",
Tasks.tasks.Documents : "Documents",
Tasks.tasks.Postman1 : "Postman Pat",
Tasks.tasks.ShakingupTeller : "Shaking up the Teller",
Tasks.tasks.Punisher1 : "The Punisher",
Tasks.tasks.Punisher2 : "The Punisher",
Tasks.tasks.Punisher3 : "The Punisher",
Tasks.tasks.Punisher4 : "The Punisher",
Tasks.tasks.Punisher5 : "The Punisher",
Tasks.tasks.Punisher6 : "The Punisher",
Tasks.tasks.Anesthesia : "Anesthesia",
Tasks.tasks.Grenadier : "Grenadier",
Tasks.tasks.TestDrive1 : "Test Drive",
Tasks.tasks.Mediator : "Perfect Mediator",
Tasks.tasks.PolikhimHobo : "Polikhim Hobo",
Tasks.tasks.Regulated : "Regulated Materials",
Tasks.tasks.BigCustomer : "Big Customer",
Tasks.tasks.Intimidator : "Intimidator",
Tasks.tasks.EasyJob1 : "Easy Job",
Tasks.tasks.EasyJob2 : "Easy Job",
Tasks.tasks.Recon : "Reconnaissance",
Tasks.tasks.Shortage : "Shortage",
Tasks.tasks.Aq1 : "Operation Aquarius",
Tasks.tasks.Aq2 : "Operation Aquarius",
Tasks.tasks.Gasan1 : "Sanitary Standards",
Tasks.tasks.Gasan2 : "Sanitary Standards",
Tasks.tasks.Painkill : "Painkiller",
Tasks.tasks.Pharm : "Pharmacist",
Tasks.tasks.DHistory : "Disease History",
Tasks.tasks.Car : "Car Repair",
Tasks.tasks.Supply : "Supply Plans",
Tasks.tasks.HCP1 : "Health Care Privacy",
Tasks.tasks.HCP2 : "Health Care Privacy",
Tasks.tasks.HCP3 : "Health Care Privacy",
Tasks.tasks.HCP4 : "Health Care Privacy",
Tasks.tasks.Athlete : "Athlete",
Tasks.tasks.PClinic : "Private Clinic",
Tasks.tasks.HCP5 : "Health Care Privacy",
Tasks.tasks.Decontam : "Decontamination Service",
Tasks.tasks.Wares : "General Wares",
Tasks.tasks.Coll1 : "Colleagues",
Tasks.tasks.Coll2 : "Colleagues",
Tasks.tasks.Coll3 : "Colleagues",
Tasks.tasks.Postman2 : "Postman Pat",
Tasks.tasks.Curiosity : "Out of Curiosity",
Tasks.tasks.Crisis : "Crisis",
Tasks.tasks.Seaside : "Seaside Vacation",
Tasks.tasks.LostContact : "Lost Contact",
Tasks.tasks.Trafficking : "Drug Trafficking",
Tasks.tasks.Supplier : "Supplier",
Tasks.tasks.Extortion : "Extortion",
Tasks.tasks.Stirrup : "Stirrup",
Tasks.tasks.FlashDrives1 : "What's on the Flash Drive?",
Tasks.tasks.GoldenSwag : "Golden Swag",
Tasks.tasks.Chem1 : "Chemical",
Tasks.tasks.Chem2 : "Chemical",
Tasks.tasks.Chem3 : "Chemical",
Tasks.tasks.Chem4 : "Chemical",
Tasks.tasks.Vit1 : "Vitamins",
Tasks.tasks.Vit2 : "Vitamins",
Tasks.tasks.FFtW1 : "Friend from the West",
Tasks.tasks.FFtW2 : "Friend from the West",
Tasks.tasks.LL1 : "Lend-Lease",
Tasks.tasks.Setup : "Setup",
Tasks.tasks.Informed : "Informed Means Armed",
Tasks.tasks.Chumming : "Chumming",
Tasks.tasks.Bullshit : "Bullshit",
Tasks.tasks.Flint : "Flint",
Tasks.tasks.KindaSabotage : "Kind of Sabotage",
Tasks.tasks.RiggedGame : "Rigged Game",
Tasks.tasks.SafeCorridor : "Safe Corridor",
Tasks.tasks.LongRoad : "Long Road",
Tasks.tasks.MissingCargo : "Missing Cargo",
Tasks.tasks.Fishing : "Fishing Gear",
Tasks.tasks.TigrSafari : "Tigr Safari",
Tasks.tasks.ScrapMetal : "Scrap Metal",
Tasks.tasks.EagleEye : "Eagle Eye",
Tasks.tasks.Blueberry1 : "Humanitarian Supplies",
Tasks.tasks.Cult1 : "The Cult",
Tasks.tasks.Cult2 : "The Cult",
Tasks.tasks.SpaTour1 : "Spa Tour",
Tasks.tasks.SpaTour2 : "Spa Tour",
Tasks.tasks.SpaTour3 : "Spa Tour",
Tasks.tasks.SpaTour4 : "Spa Tour",
Tasks.tasks.SpaTour5 : "Spa Tour",
Tasks.tasks.SpaTour6 : "Spa Tour",
Tasks.tasks.SpaTour7 : "Spa Tour",
Tasks.tasks.Cargo1 : "Cargo X",
Tasks.tasks.Cargo2 : "Cargo X",
Tasks.tasks.Cargo3 : "Cargo X",
Tasks.tasks.WetJob1 : "Wet Job",
Tasks.tasks.WetJob2 : "Wet Job",
Tasks.tasks.WetJob3 : "Wet Job",
Tasks.tasks.WetJob4 : "Wet Job",
Tasks.tasks.WetJob5 : "Wet Job",
Tasks.tasks.WetJob6 : "Wet Job",
Tasks.tasks.TheGuide : "The Guide",
Tasks.tasks.Samples : "Samples",
Tasks.tasks.Terragroup : "Terragroup Employee",
Tasks.tasks.LL2 : "Lend-Lease",
Tasks.tasks.Blueberry2 : "Peacekeeping Mission",
Tasks.tasks.ClassTech : "Classified Technologies",
Tasks.tasks.RevisReserve : "Revision",
Tasks.tasks.Cargo4 : "Cargo X",
Tasks.tasks.Insomnia : "Insomnia",
Tasks.tasks.Overpopulation : "Overpopulation",
Tasks.tasks.RevisLighthouse : "Revision",
Tasks.tasks.Intro : "Introduction",
Tasks.tasks.GS1 : "Gunsmith",
Tasks.tasks.GS2 : "Gunsmith",
Tasks.tasks.GS3 : "Gunsmith",
Tasks.tasks.GS4 : "Gunsmith",
Tasks.tasks.GS5 : "Gunsmith",
Tasks.tasks.GS6 : "Gunsmith",
Tasks.tasks.GS7 : "Gunsmith",
Tasks.tasks.GS8 : "Gunsmith",
Tasks.tasks.GS9 : "Gunsmith",
Tasks.tasks.GS10 : "Gunsmith",
Tasks.tasks.GS11 : "Gunsmith",
Tasks.tasks.GS12 : "Gunsmith",
Tasks.tasks.GS13 : "Gunsmith",
Tasks.tasks.GS14 : "Gunsmith",
Tasks.tasks.GS15 : "Gunsmith",
Tasks.tasks.GS16 : "Gunsmith",
Tasks.tasks.GS17 : "Gunsmith",
Tasks.tasks.GS18 : "Gunsmith",
Tasks.tasks.GS19 : "Gunsmith",
Tasks.tasks.GS20 : "Gunsmith",
Tasks.tasks.GS21 : "Gunsmith",
Tasks.tasks.GS22 : "Gunsmith",
Tasks.tasks.Signal1 : "Signal",
Tasks.tasks.Insider : "Insider",
Tasks.tasks.Signal2 : "Signal",
Tasks.tasks.Scout : "Scout",
Tasks.tasks.SurpGoods : "Surplus Goods",
Tasks.tasks.BackDoor : "Back Door",
Tasks.tasks.Signal3 : "Signal",
Tasks.tasks.Signal4 : "Signal",
Tasks.tasks.Farming1 : "Farming",
Tasks.tasks.Farming2 : "Farming",
Tasks.tasks.BadHabit : "Bad Habit",
Tasks.tasks.Farming3 : "Farming",
Tasks.tasks.Farming4 : "Farming",
Tasks.tasks.PsychoSniper : "Psycho Sniper",
Tasks.tasks.ShooterBorn : "A Shooter Born In Heaven",
Tasks.tasks.Fertilizers : "Fertilizers",
Tasks.tasks.Import : "Import",
Tasks.tasks.ChemCloset : "Chemical Closet",
Tasks.tasks.CorpoSecret : "Corporate Secrets",
Tasks.tasks.EnergyCrisis : "Energy Crisis",
Tasks.tasks.Broadcast1 : "Broadcast",
Tasks.tasks.OnlyBusiness : "Only Business",
Tasks.tasks.MUGA : "Make ULTRA Great Again",
Tasks.tasks.BigSale : "Big Sale",
Tasks.tasks.FuelMatter : "A Fuel Matter",
Tasks.tasks.Inventory : "Inventory Check",
Tasks.tasks.Blood1 : "The Blood of War",
Tasks.tasks.DressedtoKill : "Dressed to Kill",
Tasks.tasks.Gratitude : "Gratitude",
Tasks.tasks.Delivery : "Hot Delivery",
Tasks.tasks.Scav : "Scavenger",
Tasks.tasks.SalesNight : "Sales Night",
Tasks.tasks.Data1 : "Database",
Tasks.tasks.Data2 : "Database",
Tasks.tasks.Minibus : "Minibus",
Tasks.tasks.Sew1 : "Sew it Good",
Tasks.tasks.Blood2 : "The Blood of War",
Tasks.tasks.Blood3 : "The Blood of War",
Tasks.tasks.Sew2 : "Sew it Good",
Tasks.tasks.KeytoSuccess : "The Key to Success",
Tasks.tasks.NoFuss : "No Fuss Needed",
Tasks.tasks.Supervisor : "Supervisor",
Tasks.tasks.Sew3 : "Sew it Good",
Tasks.tasks.LHinaC1 : "Living High is Not a Crime",
Tasks.tasks.LHinaC2 : "Living High is Not a Crime",
Tasks.tasks.Sew4 : "Sew it Good",
Tasks.tasks.Charisma : "Charisma Brings Success",
Tasks.tasks.Acquaintance : "Acquaintance",
Tasks.tasks.Unprotected : "The Survivalist Path",
Tasks.tasks.Thrifty : "The Survivalist Path",
Tasks.tasks.Zhivchik : "The Survivalist Path",
Tasks.tasks.Wounded : "The Survivalist Path",
Tasks.tasks.ToughGuy : "The Survivalist Path",
Tasks.tasks.CourtesyVisit : "Courtesy Visit",
Tasks.tasks.Nostalgia : "Nostalgia",
Tasks.tasks.Junkie : "The Survivalist Path",
Tasks.tasks.Eagle : "The Survivalist Path",
Tasks.tasks.Medic : "The Survivalist Path",
Tasks.tasks.Ambulance : "Ambulance",
Tasks.tasks.SecurePerimeter : "The Huntsman Path",
Tasks.tasks.Reserve : "Reserve",
Tasks.tasks.ForestCleaning : "The Huntsman Path",
Tasks.tasks.Controller : "The Huntsman Path",
Tasks.tasks.EvilWatchman : "The Huntsman Path",
Tasks.tasks.FishingPlace : "Fishing Place",
Tasks.tasks.Trophy : "The Huntsman Path",
Tasks.tasks.Justice : "The Huntsman Path",
Tasks.tasks.Sellout : "The Huntsman Path",
Tasks.tasks.WoodsKeeper : "The Huntsman Path",
Tasks.tasks.HuntingTrip : "Hunting Trip",
Tasks.tasks.FactoryChief : "The Huntsman Path",
Tasks.tasks.Eraser1 : "The Huntsman Path",
Tasks.tasks.Eraser2 : "The Huntsman Path",
Tasks.tasks.TarkShoot1 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot2 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot3 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot4 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot5 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot6 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot7 : "The Tarkov Shooter",
Tasks.tasks.TarkShoot8 : "The Tarkov Shooter",
Tasks.tasks.FlashDrives2 : "Shady Business",
Tasks.tasks.Sadist : "The Huntsman Path",
Tasks.tasks.PestControl : "Pest Control",
Tasks.tasks.Hermit : "Hermit",
Tasks.tasks.Outcasts : "The Huntsman Path",
Tasks.tasks.StrayDogs : "Stray Dogs",
Tasks.tasks.Sausage : "The Delicious Sausage",
Tasks.tasks.OldFiresteel: "",
Tasks.tasks.AntiqueAxe: "",
Tasks.tasks.AntiqueBook: "",
Tasks.tasks.FireKlean: "",
Tasks.tasks.GoldenCock: "",
Tasks.tasks.Yeehaw: "",
Tasks.tasks.BeardOil: "",
Tasks.tasks.GPhone: "",
Tasks.tasks.DevilDog: "",
Tasks.tasks.Sprats: "",
Tasks.tasks.Mustache: "",
Tasks.tasks.Kotton: "",
Tasks.tasks.LupoBeans: "",
Tasks.tasks.Pestily: "",
Tasks.tasks.Raven: "",
Tasks.tasks.Shroud: "",
Tasks.tasks.Veritas: "",
Tasks.tasks.Tea: "",
Tasks.tasks.Smoke: "",
Tasks.tasks.Armband: "",
Tasks.tasks.RatCola: "",
Tasks.tasks.LootLord: "",
Tasks.tasks.WZWallet: "",
Tasks.tasks.RatPoison: "",
Tasks.tasks.Missam: "",
Tasks.tasks.Cassette: "",
Tasks.tasks.BakeEzy: "",
Tasks.tasks.JohnB: "",
Tasks.tasks.GloriousE: "",
Tasks.tasks.RedBeard: "",
Tasks.tasks.RedPACA: "",
Tasks.tasks.Gingy: "",
Tasks.tasks.Egg: "",
Tasks.tasks.PressPass: "",
Tasks.tasks.Axel: "",
Tasks.tasks.BEARBuddy: "",
}
