class_name ItemData
extends Database

var trader_name: String = "Streamer Items"
var complete: bool = false

var TraderTasks:= [
	Tasks.tasks.OldFiresteel,
	Tasks.tasks.AntiqueAxe,
	Tasks.tasks.AntiqueBook,
	Tasks.tasks.FireKlean,
	Tasks.tasks.GoldenCock,
	Tasks.tasks.Yeehaw,
	Tasks.tasks.BeardOil,
	Tasks.tasks.GPhone,
	Tasks.tasks.DevilDog,
	Tasks.tasks.Sprats,
	Tasks.tasks.Mustache,
	Tasks.tasks.Kotton,
	Tasks.tasks.LupoBeans,
	Tasks.tasks.Pestily,
	Tasks.tasks.Raven,
	Tasks.tasks.Shroud,
	Tasks.tasks.Veritas,
	Tasks.tasks.Tea,
	Tasks.tasks.Smoke,
	Tasks.tasks.Armband,
	Tasks.tasks.RatCola,
	Tasks.tasks.LootLord,
	Tasks.tasks.WZWallet,
	Tasks.tasks.RatPoison,
	Tasks.tasks.Missam,
	Tasks.tasks.BakeEzy,
	Tasks.tasks.JohnB,
	Tasks.tasks.GloriousE,
	Tasks.tasks.RedBeard,
	Tasks.tasks.RedPACA,
	Tasks.tasks.Gingy,
	Tasks.tasks.Egg,
	Tasks.tasks.PressPass,
	Tasks.tasks.Axel,
	Tasks.tasks.BEARBuddy
]

const TaskNames:= {
	Tasks.tasks.OldFiresteel : "Old Firesteel",
	Tasks.tasks.AntiqueAxe : "Antique Axe",
	Tasks.tasks.AntiqueBook : "Battered Antique Book",
	Tasks.tasks.FireKlean : "FireKlean Gun Lube",
	Tasks.tasks.GoldenCock : "Golden Rooster Figurine",
	Tasks.tasks.Yeehaw : "Silver Badge",
	Tasks.tasks.BeardOil : "Deadlyslob's Bear Oil",
	Tasks.tasks.GPhone : "Golden 1GPhone Smartphone",
	Tasks.tasks.DevilDog : "Jar of DevilDog Mayo",
	Tasks.tasks.Sprats : "Can of sprats",
	Tasks.tasks.Mustache : "Fake mustache",
	Tasks.tasks.Kotton : "Kotton Beanie",
	Tasks.tasks.LupoBeans : "Can of Dr. Lupo's Coffee Beans",
	Tasks.tasks.Pestily : "Pestily Plague Mask",
	Tasks.tasks.Raven : "Raven Figurine",
	Tasks.tasks.Shroud : "Shroud Half-Mask",
	Tasks.tasks.Veritas : "Veritas Guitar Pick",
	Tasks.tasks.Tea : "42 Signature Blend English Tea",
	Tasks.tasks.Smoke : "Smoke Balaclava",
	Tasks.tasks.Armband : "Armband (Evasion)",
	Tasks.tasks.RatCola : "Can of RatCola soda",
	Tasks.tasks.LootLord : "Loot Lord Plushie",
	Tasks.tasks.WZWallet : "WillerZ Wallet",
	Tasks.tasks.RatPoison : "LVNDMARK's Rat Poison",
	Tasks.tasks.Missam : "Missam Forklift Key",
	Tasks.tasks.Cassette : "Cyborg Killer Movie Cassete",
	Tasks.tasks.BakeEzy : "BakeEzy Cook Book",
	Tasks.tasks.JohnB : "JohnB Liquid DNB Glasses",
	Tasks.tasks.GloriousE : "Glorious E Lightweight Armored Mask",
	Tasks.tasks.RedBeard : "Baddie's Red Beard",
	Tasks.tasks.RedPACA : "DRD Body Armor",
	Tasks.tasks.Gingy : "Gingy Keychain",
	Tasks.tasks.Egg : "Golden Egg",
	Tasks.tasks.PressPass : "Noiceguy's Press Pass",
	Tasks.tasks.Axel: "Axel Parrot Figurine",
	Tasks.tasks.BEARBuddy : "BEAR Buddy Plush Toy"
}
