class_name JaegerData
extends Database

var trader_name: String = "Jaeger"
var complete: bool = false

var TraderTasks:= [
	Tasks.tasks.Acquaintance,
	Tasks.tasks.Unprotected,
	Tasks.tasks.Thrifty,
	Tasks.tasks.Zhivchik,
	Tasks.tasks.Wounded,
	Tasks.tasks.ToughGuy,
	Tasks.tasks.CourtesyVisit,
	Tasks.tasks.Nostalgia,
	Tasks.tasks.Junkie,
	Tasks.tasks.Eagle,
	Tasks.tasks.Medic,
	Tasks.tasks.Ambulance,
	Tasks.tasks.SecurePerimeter,
	Tasks.tasks.Reserve,
	Tasks.tasks.ForestCleaning,
	Tasks.tasks.Controller,
	Tasks.tasks.EvilWatchman,
	Tasks.tasks.FishingPlace,
	Tasks.tasks.Trophy,
	Tasks.tasks.Justice,
	Tasks.tasks.Sellout,
	Tasks.tasks.WoodsKeeper,
	Tasks.tasks.HuntingTrip,
	Tasks.tasks.FactoryChief,
	Tasks.tasks.Eraser1,
	Tasks.tasks.Eraser2,
	Tasks.tasks.TarkShoot1,
	Tasks.tasks.TarkShoot2,
	Tasks.tasks.TarkShoot3,
	Tasks.tasks.TarkShoot4,
	Tasks.tasks.TarkShoot5,
	Tasks.tasks.TarkShoot6,
	Tasks.tasks.TarkShoot7,
	Tasks.tasks.TarkShoot8,
	Tasks.tasks.FlashDrives2,
	Tasks.tasks.Sadist,
	Tasks.tasks.PestControl,
	Tasks.tasks.Hermit,
	Tasks.tasks.Outcasts,
	Tasks.tasks.StrayDogs,
	Tasks.tasks.Sausage,
]

const TaskNames:= {
	Tasks.tasks.Acquaintance : "Acquaintance",
	Tasks.tasks.Unprotected : "The Survivalist Path - Unprotected but Dangerous",
	Tasks.tasks.Thrifty : "The Survivalist Path - Thrifty",
	Tasks.tasks.Zhivchik : "The Survivalist Path - Zhivchik",
	Tasks.tasks.Wounded : "The Survivalist Path - Wounded Beast",
	Tasks.tasks.ToughGuy : "The Survivalist Path - Tough Guy",
	Tasks.tasks.CourtesyVisit : "Courtesy Visit",
	Tasks.tasks.Nostalgia : "Nostalgia",
	Tasks.tasks.Junkie : "The Survivalist Path - Junkie",
	Tasks.tasks.Eagle : "The Survivalist Path - Eagle-Owl",
	Tasks.tasks.Medic : "The Survivalist Path - Combat Medic",
	Tasks.tasks.Ambulance : "Ambulance",
	Tasks.tasks.SecurePerimeter : "The Huntsman Path - Secure Perimeter",
	Tasks.tasks.Reserve : "Reserve",
	Tasks.tasks.ForestCleaning : "The Huntsman Path - Forest Cleaning",
	Tasks.tasks.Controller : "The Huntsman Path - Controller",
	Tasks.tasks.EvilWatchman : "The Huntsman Path - Evil Watchman",
	Tasks.tasks.FishingPlace : "Fishing Place",
	Tasks.tasks.Trophy : "The Huntsman Path - Trophy",
	Tasks.tasks.Justice : "The Huntsman Path - Justice",
	Tasks.tasks.Sellout : "The Huntsman Path - Sellout",
	Tasks.tasks.WoodsKeeper : "The Huntsman Path - Woods Keeper",
	Tasks.tasks.HuntingTrip : "Hunting Trip",
	Tasks.tasks.FactoryChief : "The Huntsman Path - Factory Chief",
	Tasks.tasks.Eraser1 : "The Huntsman Path - Eraser - Part 1",
	Tasks.tasks.Eraser2 : "The Huntsman Path - Eraser - Part 2",
	Tasks.tasks.TarkShoot1 : "The Tarkov Shooter - Part 1",
	Tasks.tasks.TarkShoot2 : "The Tarkov Shooter - Part 2",
	Tasks.tasks.TarkShoot3 : "The Tarkov Shooter - Part 3",
	Tasks.tasks.TarkShoot4 : "The Tarkov Shooter - Part 4",
	Tasks.tasks.TarkShoot5 : "The Tarkov Shooter - Part 5",
	Tasks.tasks.TarkShoot6 : "The Tarkov Shooter - Part 6",
	Tasks.tasks.TarkShoot7 : "The Tarkov Shooter - Part 7",
	Tasks.tasks.TarkShoot8 : "The Tarkov Shooter - Part 8",
	Tasks.tasks.FlashDrives2 : "Shady Business",
	Tasks.tasks.Sadist : "The Huntsman Path - Sadist",
	Tasks.tasks.PestControl : "Pest Control",
	Tasks.tasks.Hermit : "Hermit",
	Tasks.tasks.Outcasts : "The Huntsman Path - Outcasts",
	Tasks.tasks.StrayDogs : "Stray Dogs",
	Tasks.tasks.Sausage : "The Delicious Sausage",
}
