class_name MechanicData
extends Node

var trader_name: String = "Mechanic"
var complete: bool = false

var TraderTasks:= [
	Tasks.tasks.GS1,
	Tasks.tasks.Intro,
	Tasks.tasks.GS2,
	Tasks.tasks.GS3,
	Tasks.tasks.GS5,
	Tasks.tasks.GS6,
	Tasks.tasks.GS7,
	Tasks.tasks.GS8,
	Tasks.tasks.GS9,
	Tasks.tasks.GS10,
	Tasks.tasks.GS11,
	Tasks.tasks.GS12,
	Tasks.tasks.GS13,
	Tasks.tasks.GS14,
	Tasks.tasks.GS15,
	Tasks.tasks.GS16,
	Tasks.tasks.GS17,
	Tasks.tasks.GS18,
	Tasks.tasks.GS19,
	Tasks.tasks.GS20,
	Tasks.tasks.GS21,
	Tasks.tasks.GS22,
	Tasks.tasks.Signal1,
	Tasks.tasks.Insider,
	Tasks.tasks.Signal2,
	Tasks.tasks.Scout,
	Tasks.tasks.SurpGoods,
	Tasks.tasks.BackDoor,
	Tasks.tasks.Signal3,
	Tasks.tasks.Signal4,
	Tasks.tasks.Farming1,
	Tasks.tasks.Farming2,
	Tasks.tasks.BadHabit,
	Tasks.tasks.Farming3,
	Tasks.tasks.Farming4,
	Tasks.tasks.PsychoSniper,
	Tasks.tasks.ShooterBorn,
	Tasks.tasks.Fertilizers,
	Tasks.tasks.Import,
	Tasks.tasks.ChemCloset,
	Tasks.tasks.CorpoSecret,
	Tasks.tasks.EnergyCrisis,
	Tasks.tasks.Broadcast1
]

const TaskNames:= {
	Tasks.tasks.Intro : "Introduction",
	Tasks.tasks.GS1 : "Gunsmith - Part 1",
	Tasks.tasks.GS2 : "Gunsmith - Part 2",
	Tasks.tasks.GS3 : "Gunsmith - Part 3",
	Tasks.tasks.GS4 : "Gunsmith - Part 4",
	Tasks.tasks.GS5 : "Gunsmith - Part 5",
	Tasks.tasks.GS6 : "Gunsmith - Part 6",
	Tasks.tasks.GS7 : "Gunsmith - Part 7",
	Tasks.tasks.GS8 : "Gunsmith - Part 8",
	Tasks.tasks.GS9 : "Gunsmith - Part 9",
	Tasks.tasks.GS10 : "Gunsmith - Part 10",
	Tasks.tasks.GS11 : "Gunsmith - Part 11",
	Tasks.tasks.GS12 : "Gunsmith - Part 12",
	Tasks.tasks.GS13 : "Gunsmith - Part 13",
	Tasks.tasks.GS14 : "Gunsmith - Part 14",
	Tasks.tasks.GS15 : "Gunsmith - Part 15",
	Tasks.tasks.GS16 : "Gunsmith - Part 16",
	Tasks.tasks.GS17 : "Gunsmith - Part 17",
	Tasks.tasks.GS18 : "Gunsmith - Part 18",
	Tasks.tasks.GS19 : "Gunsmith - Part 19",
	Tasks.tasks.GS20 : "Gunsmith - Part 20",
	Tasks.tasks.GS21 : "Gunsmith - Part 21",
	Tasks.tasks.GS22 : "Gunsmith - Part 22",
	Tasks.tasks.Signal1 : "Signal - Part 1",
	Tasks.tasks.Insider : "Insider",
	Tasks.tasks.Signal2 : "Signal - Part 2",
	Tasks.tasks.Scout : "Scout",
	Tasks.tasks.SurpGoods : "Surplus Goods",
	Tasks.tasks.BackDoor : "Back Door",
	Tasks.tasks.Signal3 : "Signal - Part 3",
	Tasks.tasks.Signal4 : "Signal - Part 4",
	Tasks.tasks.Farming1 : "Farming - Part 1",
	Tasks.tasks.Farming2 : "Farming - Part 2",
	Tasks.tasks.BadHabit : "Bad Habit",
	Tasks.tasks.Farming3 : "Farming - Part 3",
	Tasks.tasks.Farming4 : "Farming - Part 4",
	Tasks.tasks.PsychoSniper : "Psycho Sniper",
	Tasks.tasks.ShooterBorn : "A Shooter Born In Heaven",
	Tasks.tasks.Fertilizers : "Fertilizers",
	Tasks.tasks.Import : "Import",
	Tasks.tasks.ChemCloset : "Chemical Closet",
	Tasks.tasks.CorpoSecret : "Corporate Secrets",
	Tasks.tasks.EnergyCrisis : "Energy Crisis",
	Tasks.tasks.Broadcast1 : "Broadcast - Part 1"
}

func run_check() -> void:
	pass
