class_name PeacekeeperData
extends Database

var trader_name: String = "Peacekeeper"
var complete: bool = false

var TraderTasks:= [
	Tasks.tasks.Fishing,
	Tasks.tasks.TigrSafari,
	Tasks.tasks.ScrapMetal,
	Tasks.tasks.EagleEye,
	Tasks.tasks.Blueberry1,
	Tasks.tasks.Cult1,
	Tasks.tasks.Cult2,
	Tasks.tasks.SpaTour1,
	Tasks.tasks.SpaTour2,
	Tasks.tasks.SpaTour3,
	Tasks.tasks.SpaTour4,
	Tasks.tasks.SpaTour5,
	Tasks.tasks.SpaTour6,
	Tasks.tasks.SpaTour7,
	Tasks.tasks.Cargo1,
	Tasks.tasks.Cargo2,
	Tasks.tasks.Cargo3,
	Tasks.tasks.WetJob1,
	Tasks.tasks.WetJob2,
	Tasks.tasks.WetJob3,
	Tasks.tasks.WetJob4,
	Tasks.tasks.WetJob5,
	Tasks.tasks.WetJob6,
	Tasks.tasks.TheGuide,
	Tasks.tasks.Samples,
	Tasks.tasks.Terragroup,
	Tasks.tasks.LL2,
	Tasks.tasks.Blueberry2,
	Tasks.tasks.ClassTech,
	Tasks.tasks.RevisReserve,
	Tasks.tasks.Cargo4,
	Tasks.tasks.Insomnia,
	Tasks.tasks.Overpopulation,
]

const TaskNames:= {
	Tasks.tasks.Fishing : "Fishing Gear",
	Tasks.tasks.TigrSafari : "Tigr Safari",
	Tasks.tasks.ScrapMetal : "Scrap Metal",
	Tasks.tasks.EagleEye : "Eagle Eye",
	Tasks.tasks.Blueberry1 : "Humanitarian Supplies",
	Tasks.tasks.Cult1 : "The Cult - Part 1",
	Tasks.tasks.Cult2 : "The Cult - Part 2",
	Tasks.tasks.SpaTour1 : "Spa Tour - Part 1",
	Tasks.tasks.SpaTour2 : "Spa Tour - Part 2",
	Tasks.tasks.SpaTour3 : "Spa Tour - Part 3",
	Tasks.tasks.SpaTour4 : "Spa Tour - Part 4",
	Tasks.tasks.SpaTour5 : "Spa Tour - Part 5",
	Tasks.tasks.SpaTour6 : "Spa Tour - Part 6",
	Tasks.tasks.SpaTour7 : "Spa Tour - Part 7",
	Tasks.tasks.Cargo1 : "Cargo X - Part 1",
	Tasks.tasks.Cargo2 : "Cargo X - Part 2",
	Tasks.tasks.Cargo3 : "Cargo X - Part 3",
	Tasks.tasks.WetJob1 : "Wet Job - Part 1",
	Tasks.tasks.WetJob2 : "Wet Job - Part 2",
	Tasks.tasks.WetJob3 : "Wet Job - Part 3",
	Tasks.tasks.WetJob4 : "Wet Job - Part 4",
	Tasks.tasks.WetJob5 : "Wet Job - Part 5",
	Tasks.tasks.WetJob6 : "Wet Job - Part 6",
	Tasks.tasks.TheGuide : "The Guide",
	Tasks.tasks.Samples : "Samples",
	Tasks.tasks.Terragroup : "Terragroup Employee",
	Tasks.tasks.LL2 : "Lend-Lease - Part 2",
	Tasks.tasks.Blueberry2 : "Peacekeeping Mission",
	Tasks.tasks.ClassTech : "Classified Technologies",
	Tasks.tasks.RevisReserve : "Revision (Reserve)",
	Tasks.tasks.Cargo4 : "Cargo X - Part 4",
	Tasks.tasks.Insomnia : "Insomnia",
	Tasks.tasks.Overpopulation : "Overpopulation",
	Tasks.tasks.RevisLighthouse : "Revision (Lighthouse)",
}

func run_check() -> void:
	pass
